<?php

namespace Database\Seeders;

use App\Models\Cabang;
use App\Models\Terminal;
use App\Models\Vendor;
use Illuminate\Database\Seeder;

class TerminalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Seed Vendors
        $vendorsJson = <<<'JSON'
[
    "ASSINDO",
    "HIBAH",
    "HIBAH SRISHINDU",
    "SRISHINDU"
]
JSON;
        $vendorMap = [];
        foreach (json_decode($vendorsJson, true) as $vName) {
            $v = Vendor::firstOrCreate(['nama_vendor' => $vName]);
            $vendorMap[$vName] = $v->id;
        }

        // 2. Seed Cabang
        $cabangsJson = <<<'JSON'
[
    {
        "kode": "001",
        "nama": "Utama Palu",
        "label": "001-Utama Palu",
        "urutan": 1
    },
    {
        "kode": "002",
        "nama": "Toli-Toli",
        "label": "002-Toli-Toli",
        "urutan": 2
    },
    {
        "kode": "003",
        "nama": "Poso",
        "label": "003-Poso",
        "urutan": 3
    },
    {
        "kode": "004",
        "nama": "Luwuk",
        "label": "004-Luwuk",
        "urutan": 4
    },
    {
        "kode": "005",
        "nama": "Bungku",
        "label": "005-Bungku",
        "urutan": 5
    },
    {
        "kode": "006",
        "nama": "Salakan",
        "label": "006-Salakan",
        "urutan": 6
    },
    {
        "kode": "007",
        "nama": "Sigi",
        "label": "007-Sigi",
        "urutan": 7
    },
    {
        "kode": "008",
        "nama": "Palu Barat",
        "label": "008-Palu Barat",
        "urutan": 8
    },
    {
        "kode": "009",
        "nama": "Jakarta",
        "label": "009-Jakarta",
        "urutan": 9
    },
    {
        "kode": "101",
        "nama": "Donggala",
        "label": "101-Donggala",
        "urutan": 10
    },
    {
        "kode": "102",
        "nama": "Parigi",
        "label": "102-Parigi",
        "urutan": 11
    },
    {
        "kode": "103",
        "nama": "Lambunu",
        "label": "103-Lambunu",
        "urutan": 12
    },
    {
        "kode": "104",
        "nama": "KCP Labean",
        "label": "104-KCP Labean",
        "urutan": 13
    },
    {
        "kode": "105",
        "nama": "Tolai",
        "label": "105-Tolai",
        "urutan": 14
    },
    {
        "kode": "106",
        "nama": "Tinombo",
        "label": "106-Tinombo",
        "urutan": 15
    },
    {
        "kode": "107",
        "nama": "Tinombala",
        "label": "107-Tinombala",
        "urutan": 16
    },
    {
        "kode": "108",
        "nama": "Kotaraya",
        "label": "108-Kotaraya",
        "urutan": 17
    },
    {
        "kode": "201",
        "nama": "Buol",
        "label": "201-Buol",
        "urutan": 18
    },
    {
        "kode": "202",
        "nama": "Soni",
        "label": "202-Soni",
        "urutan": 19
    },
    {
        "kode": "211",
        "nama": "Paleleh",
        "label": "211-Paleleh",
        "urutan": 20
    },
    {
        "kode": "301",
        "nama": "Ampana",
        "label": "301-Ampana",
        "urutan": 21
    },
    {
        "kode": "302",
        "nama": "Wakai",
        "label": "302-Wakai",
        "urutan": 22
    },
    {
        "kode": "303",
        "nama": "Tentena",
        "label": "303-Tentena",
        "urutan": 23
    },
    {
        "kode": "304",
        "nama": "Pendolo",
        "label": "304-Pendolo",
        "urutan": 24
    },
    {
        "kode": "305",
        "nama": "Napu",
        "label": "305-Napu",
        "urutan": 25
    },
    {
        "kode": "306",
        "nama": "Tambarana",
        "label": "306-Tambarana",
        "urutan": 26
    },
    {
        "kode": "401",
        "nama": "Kolonodale",
        "label": "401-Kolonodale",
        "urutan": 27
    },
    {
        "kode": "402",
        "nama": "Banggai Laut",
        "label": "402-Banggai Laut",
        "urutan": 28
    },
    {
        "kode": "403",
        "nama": "Beteleme",
        "label": "403-Beteleme",
        "urutan": 29
    },
    {
        "kode": "404",
        "nama": "Batui",
        "label": "404-Batui",
        "urutan": 30
    },
    {
        "kode": "405",
        "nama": "Toili",
        "label": "405-Toili",
        "urutan": 31
    },
    {
        "kode": "406",
        "nama": "Masama",
        "label": "406-Masama",
        "urutan": 32
    },
    {
        "kode": "407",
        "nama": "Bunta",
        "label": "407-Bunta",
        "urutan": 33
    },
    {
        "kode": "411",
        "nama": "Mamosalato",
        "label": "411-Mamosalato",
        "urutan": 34
    },
    {
        "kode": "412",
        "nama": "Tomata",
        "label": "412-Tomata",
        "urutan": 35
    },
    {
        "kode": "413",
        "nama": "Baturube",
        "label": "413-Baturube",
        "urutan": 36
    },
    {
        "kode": "501",
        "nama": "Bahomotefe",
        "label": "501-Bahomotefe",
        "urutan": 37
    },
    {
        "kode": "502",
        "nama": "Bahodopi",
        "label": "502-Bahodopi",
        "urutan": 38
    },
    {
        "kode": "701",
        "nama": "Kulawi",
        "label": "701-Kulawi",
        "urutan": 39
    },
    {
        "kode": "801",
        "nama": "Capem Tawaeli",
        "label": "801-Capem Tawaeli",
        "urutan": 40
    }
]
JSON;
        $cabangMap = [];
        foreach (json_decode($cabangsJson, true) as $cData) {
            $c = Cabang::firstOrCreate(
                ['kode_cabang' => $cData['kode']],
                [
                    'nama_cabang' => $cData['nama'],
                    'label_cabang' => $cData['label'],
                    'urutan' => $cData['urutan'],
                ]
            );
            $cabangMap[$cData['kode']] = $c->id;
        }

        // 3. Seed Terminals (136 Units)
        $terminalsJson = <<<'JSON'
[
    {
        "no": 1,
        "profil": "WCR.KCU1",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 1,
        "nama_lokasi": "RS Undata Palu",
        "ip_address": "10.10.10.26",
        "luno": "0200",
        "port": "8191",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG701702",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 2,
        "profil": "DBL.HERO",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 2,
        "nama_lokasi": "Grand Hero",
        "ip_address": "172.16.55.2",
        "luno": "0013",
        "port": "8060",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06743",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 3,
        "profil": "DBL.GBNR",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 3,
        "nama_lokasi": "Gubernur Sulteng",
        "ip_address": "175.12.8.2",
        "luno": "0002",
        "port": "8068",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06730",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 4,
        "profil": "DBL.SAMS",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 4,
        "nama_lokasi": "Kantor Samsat",
        "ip_address": "175.12.12.2",
        "luno": "0018",
        "port": "8069",
        "vendor_name": "HIBAH SRISHINDU",
        "serial_number": "522FDC20645",
        "denom": "100",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 5,
        "profil": "DBL.WALIKOTA",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 5,
        "nama_lokasi": "Galeri Disabilitas Cabang Uatama",
        "ip_address": "175.12.11.2",
        "luno": "0076",
        "port": "8066",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05381",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 6,
        "profil": "DBL.FTRA",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 6,
        "nama_lokasi": "Alfamidi DewiSartika",
        "ip_address": "175.12.9.2",
        "luno": "0038",
        "port": "8065",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05373",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 7,
        "profil": "DBL.MRAYA",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 7,
        "nama_lokasi": "Gatsumaya ( MRAYA )",
        "ip_address": "175.12.17.2",
        "luno": "0039",
        "port": "8038",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06735",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 8,
        "profil": "DBL.BAPPEDA",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 8,
        "nama_lokasi": "Bappeda Propinsi Palu",
        "ip_address": "172.16.30.2",
        "luno": "0068",
        "port": "8002",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06753",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 9,
        "profil": "DBL.DINKES",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 9,
        "nama_lokasi": "Dinkes Sulteng",
        "ip_address": "172.16.33.2",
        "luno": "0065",
        "port": "8096",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06742",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 10,
        "profil": "DBL.DIKJAR",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 10,
        "nama_lokasi": "Dikjar Sulteng",
        "ip_address": "172.16.50.6",
        "luno": "0066",
        "port": "8040",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06719",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 11,
        "profil": "DBL.BKD",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 11,
        "nama_lokasi": "BKD Sulteng",
        "ip_address": "10.10.10.21",
        "luno": "0072",
        "port": "8019",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06733",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 12,
        "profil": "DBL.KCU6",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 12,
        "nama_lokasi": "Alfamidi Veteran Palu",
        "ip_address": "175.12.41.2",
        "luno": "0196",
        "port": "8182",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06724",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 13,
        "profil": "DBL.BNS",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 13,
        "nama_lokasi": "Deperindakop ( BNS )",
        "ip_address": "172.16.50.2",
        "luno": "0069",
        "port": "8039",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06741",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 14,
        "profil": "DBL.PERIZINAN",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 14,
        "nama_lokasi": "Kantor Perizinan Palu",
        "ip_address": "172.16.27.2",
        "luno": "0133",
        "port": "8018",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06747",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 15,
        "profil": "DBL.KCU7",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 15,
        "nama_lokasi": "Alfamidi (depan RS Samaritan)",
        "ip_address": "175.12.20.2",
        "luno": "0204",
        "port": "8046",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 04728",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 16,
        "profil": "NCR.KCU4",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 16,
        "nama_lokasi": "Galeri ATM Cabang Utama",
        "ip_address": "175.12.16.2",
        "luno": "0134",
        "port": "8076",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 211723",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 17,
        "profil": "NCR.KCU1",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 17,
        "nama_lokasi": "Galeri ATM Cabang Utama",
        "ip_address": "175.12.10.3",
        "luno": "0168",
        "port": "8143",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 96428720",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 18,
        "profil": "CRM.KCU1",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 18,
        "nama_lokasi": "Galeri ATM Cabang Utama",
        "ip_address": "172.16.50.34",
        "luno": "0176",
        "port": "8113",
        "vendor_name": "ASSINDO",
        "serial_number": "B2010D00482",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 19,
        "profil": "CRM.KCU2",
        "cabang_kode": "001",
        "cabang_text": "001-Utama Palu",
        "urutan_cabang": 19,
        "nama_lokasi": "Galeri ATM Cabang Utama",
        "ip_address": "172.16.50.38",
        "luno": "0178",
        "port": "8145",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0089",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 20,
        "profil": "DBL.TOL2",
        "cabang_kode": "002",
        "cabang_text": "002-Toli-Toli",
        "urutan_cabang": 1,
        "nama_lokasi": "Taman kota Toli-toli",
        "ip_address": "172.16.65.114",
        "luno": "0023",
        "port": "8023",
        "vendor_name": "HIBAH",
        "serial_number": "1522FDC13572",
        "denom": "50",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 21,
        "profil": "DBL.TOL4",
        "cabang_kode": "002",
        "cabang_text": "002-Toli-Toli",
        "urutan_cabang": 2,
        "nama_lokasi": "Galeri ATM Kantor Cabang Toli-toli",
        "ip_address": "172.16.49.2",
        "luno": "0037",
        "port": "8157",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05379",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 22,
        "profil": "DBL.TOL3",
        "cabang_kode": "002",
        "cabang_text": "002-Toli-Toli",
        "urutan_cabang": 3,
        "nama_lokasi": "Gardu ATM Kantor Keuangan",
        "ip_address": "10.10.10.5",
        "luno": "0033",
        "port": "8183",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05377",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 23,
        "profil": "CRM.TOLIS1",
        "cabang_kode": "002",
        "cabang_text": "002-Toli-Toli",
        "urutan_cabang": 4,
        "nama_lokasi": "Galeri ATM Kantor Cabang Toli-toli",
        "ip_address": "192.168.225.228",
        "luno": "0195",
        "port": "8165",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0090",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 24,
        "profil": "WCR.TOL5",
        "cabang_kode": "002",
        "cabang_text": "002-Toli-Toli",
        "urutan_cabang": 5,
        "nama_lokasi": "Alfamidi Nopi",
        "ip_address": "192.168.225.72",
        "luno": "0164",
        "port": "8033",
        "vendor_name": "SRISHINDU",
        "serial_number": "J821004735",
        "denom": "50",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 25,
        "profil": "YHU.TOL6",
        "cabang_kode": "002",
        "cabang_text": "002-Toli-Toli",
        "urutan_cabang": 6,
        "nama_lokasi": "Galeri ATM Kantor Cabang Toli-toli",
        "ip_address": "192.168.225.68",
        "luno": "0224",
        "port": "8249",
        "vendor_name": "ASSINDO",
        "serial_number": "H2410D00132",
        "denom": "100",
        "tipe_mesin": "YIHUA ATM",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 26,
        "profil": "NCR.POSO9",
        "cabang_kode": "003",
        "cabang_text": "003-Poso",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM RSUD Poso",
        "ip_address": "192.168.225.73",
        "luno": "0215",
        "port": "8037",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 211724",
        "denom": "50",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 27,
        "profil": "DBL.POSO2",
        "cabang_kode": "003",
        "cabang_text": "003-Poso",
        "urutan_cabang": 2,
        "nama_lokasi": "Gardu ATM Pasar Kasiguncu",
        "ip_address": "192.168.227.62",
        "luno": "0080",
        "port": "8087",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06739",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 28,
        "profil": "WCR.POSO8",
        "cabang_kode": "003",
        "cabang_text": "003-Poso",
        "urutan_cabang": 3,
        "nama_lokasi": "Gardu ATM Denzipur Poso",
        "ip_address": "175.12.39.2",
        "luno": "0214",
        "port": "8178",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG701709",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 29,
        "profil": "NCR.POSO2",
        "cabang_kode": "003",
        "cabang_text": "003-Poso",
        "urutan_cabang": 4,
        "nama_lokasi": "Gardu ATM Kantor Bupati Poso",
        "ip_address": "192.168.227.38",
        "luno": "0197",
        "port": "8079",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50738661",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 30,
        "profil": "DBL.POSO3",
        "cabang_kode": "003",
        "cabang_text": "003-Poso",
        "urutan_cabang": 5,
        "nama_lokasi": "Galeri ATM Kantor Cabang Poso",
        "ip_address": "175.12.38.2",
        "luno": "0140",
        "port": "8081",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 96428719",
        "denom": "50",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 31,
        "profil": "DBL.POSO4",
        "cabang_kode": "003",
        "cabang_text": "003-Poso",
        "urutan_cabang": 6,
        "nama_lokasi": "Galeri ATM Kantor Cabang Poso",
        "ip_address": "175.12.31.2",
        "luno": "0169",
        "port": "8105",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06757",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 32,
        "profil": "DBL.POSO5",
        "cabang_kode": "003",
        "cabang_text": "003-Poso",
        "urutan_cabang": 7,
        "nama_lokasi": "Galeri ATM Kantor Cabang Poso",
        "ip_address": "172.16.16.101",
        "luno": "0170",
        "port": "8152",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 00802",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 33,
        "profil": "CRM.POSO",
        "cabang_kode": "003",
        "cabang_text": "003-Poso",
        "urutan_cabang": 8,
        "nama_lokasi": "Galeri ATM Kantor Cabang Poso",
        "ip_address": "172.16.16.103",
        "luno": "0183",
        "port": "8185",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0103",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 34,
        "profil": "DBL.LUWUK3",
        "cabang_kode": "004",
        "cabang_text": "004-Luwuk",
        "urutan_cabang": 1,
        "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
        "ip_address": "172.16.16.104",
        "luno": "0050",
        "port": "8186",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06762",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 35,
        "profil": "DBL.LUWUK",
        "cabang_kode": "004",
        "cabang_text": "004-Luwuk",
        "urutan_cabang": 2,
        "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
        "ip_address": "172.16.17.2",
        "luno": "0003",
        "port": "8003",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06755",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 36,
        "profil": "DBL.LWK",
        "cabang_kode": "004",
        "cabang_text": "004-Luwuk",
        "urutan_cabang": 3,
        "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
        "ip_address": "172.16.17.4",
        "luno": "0015",
        "port": "8051",
        "vendor_name": "HIBAH",
        "serial_number": "1522FDC26643",
        "denom": "100",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 37,
        "profil": "WCR.LUWUK",
        "cabang_kode": "004",
        "cabang_text": "004-Luwuk",
        "urutan_cabang": 4,
        "nama_lokasi": "Gardu ATM Polsek Kintom",
        "ip_address": "192.168.225.50",
        "luno": "0213",
        "port": "8050",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG701707",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 38,
        "profil": "DBL.LUWUK5",
        "cabang_kode": "004",
        "cabang_text": "004-Luwuk",
        "urutan_cabang": 5,
        "nama_lokasi": "Gardu ATM Kantor Bupati Luwuk",
        "ip_address": "172.16.17.4",
        "luno": "0052",
        "port": "8051",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06729",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 39,
        "profil": "CRM.LUWUK",
        "cabang_kode": "004",
        "cabang_text": "004-Luwuk",
        "urutan_cabang": 6,
        "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
        "ip_address": "172.16.17.6",
        "luno": "0185",
        "port": "8078",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0099",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 40,
        "profil": "YHU.LUWUK10",
        "cabang_kode": "004",
        "cabang_text": "004-Luwuk",
        "urutan_cabang": 7,
        "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
        "ip_address": "172.16.17.5",
        "luno": "0229",
        "port": "8254",
        "vendor_name": "ASSINDO",
        "serial_number": "H2410D00133",
        "denom": "100",
        "tipe_mesin": "YIHUA ATM",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 41,
        "profil": "YHU.LUWUK11",
        "cabang_kode": "004",
        "cabang_text": "004-Luwuk",
        "urutan_cabang": 8,
        "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
        "ip_address": "172.16.17.7",
        "luno": "0230",
        "port": "8255",
        "vendor_name": "ASSINDO",
        "serial_number": "H2410D00136",
        "denom": "100",
        "tipe_mesin": "YIHUA ATM",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 42,
        "profil": "CRM.BUNGKU",
        "cabang_kode": "005",
        "cabang_text": "005-Bungku",
        "urutan_cabang": 1,
        "nama_lokasi": "Galeri ATM Kantor Cabang Bungku",
        "ip_address": "172.16.32.2",
        "luno": "0188",
        "port": null,
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0091",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 43,
        "profil": "DBL.BUN",
        "cabang_kode": "005",
        "cabang_text": "005-Bungku",
        "urutan_cabang": 2,
        "nama_lokasi": "Gardu ATM Kantor Bupati Bungku",
        "ip_address": "175.12.34.2",
        "luno": "0026",
        "port": "8109",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 07148",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 44,
        "profil": "DBL.BUN3",
        "cabang_kode": "005",
        "cabang_text": "005-Bungku",
        "urutan_cabang": 3,
        "nama_lokasi": "Gardu ATM KC Bungku lama",
        "ip_address": "175.12.5.2",
        "luno": "0048",
        "port": "8025",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06756",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 45,
        "profil": "NCR.BUNGKU1",
        "cabang_kode": "005",
        "cabang_text": "005-Bungku",
        "urutan_cabang": 4,
        "nama_lokasi": "Galeri ATM Kantor Cabang Bungku",
        "ip_address": "172.16.19.4",
        "luno": "0131",
        "port": "8048",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 96428713",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 46,
        "profil": "DBL.BUNGKU2",
        "cabang_kode": "005",
        "cabang_text": "005-Bungku",
        "urutan_cabang": 5,
        "nama_lokasi": "Gardu ATM Witaponda",
        "ip_address": "192.168.225.202",
        "luno": "0153",
        "port": "8014",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 12596",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 47,
        "profil": "DBL.SLKN",
        "cabang_kode": "006",
        "cabang_text": "006-Salakan",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM Kantor Keuangan",
        "ip_address": "175.10.7.2",
        "luno": "0036",
        "port": "8141",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05376",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 48,
        "profil": "WCR.SLKN2",
        "cabang_kode": "006",
        "cabang_text": "006-Salakan",
        "urutan_cabang": 2,
        "nama_lokasi": "Galeri ATM Kantor Cabang Salakan",
        "ip_address": "175.12.10.10",
        "luno": "0210",
        "port": "8166",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG701752",
        "denom": "50",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 49,
        "profil": "NCR.SLKN",
        "cabang_kode": "006",
        "cabang_text": "006-Salakan",
        "urutan_cabang": 3,
        "nama_lokasi": "Gardu ATM Pertokoan",
        "ip_address": "192.168.225.220",
        "luno": "0084",
        "port": "8029",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50738651",
        "denom": "50",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 50,
        "profil": "CRM.SALAKAN",
        "cabang_kode": "006",
        "cabang_text": "006-Salakan",
        "urutan_cabang": 4,
        "nama_lokasi": "Galeri ATM Kantor Cabang Salakan",
        "ip_address": "175.12.37.2",
        "luno": "0187",
        "port": "8036",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0096",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 51,
        "profil": "WCR.SLKN",
        "cabang_kode": "006",
        "cabang_text": "006-Salakan",
        "urutan_cabang": 5,
        "nama_lokasi": "Galeri ATM RSUD Salakan",
        "ip_address": "192.168.227.46",
        "luno": "0157",
        "port": "8084",
        "vendor_name": "SRISHINDU",
        "serial_number": "J821004732",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 52,
        "profil": "YHU.SLKN",
        "cabang_kode": "006",
        "cabang_text": "006-Salakan",
        "urutan_cabang": 6,
        "nama_lokasi": "KANTOR CABANG SALAKAN",
        "ip_address": "192.168.225.212",
        "luno": "0233",
        "port": "8258",
        "vendor_name": "ASSINDO",
        "serial_number": "H2410D00131",
        "denom": "100",
        "tipe_mesin": "YIHUA ATM",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 53,
        "profil": "CRM.SIGI1",
        "cabang_kode": "007",
        "cabang_text": "007-Sigi",
        "urutan_cabang": 1,
        "nama_lokasi": "Kantor Cabang Sigi",
        "ip_address": "175.12.27.2",
        "luno": "0179",
        "port": "8118",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0098",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 54,
        "profil": "NCR.KALUKUBULA",
        "cabang_kode": "007",
        "cabang_text": "007-Sigi",
        "urutan_cabang": 2,
        "nama_lokasi": "Kantor Cabang Sigi",
        "ip_address": "172.16.18.2",
        "luno": "0092",
        "port": "8170",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50737781",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 55,
        "profil": "WCR.SIGI",
        "cabang_kode": "007",
        "cabang_text": "007-Sigi",
        "urutan_cabang": 3,
        "nama_lokasi": "Puskesmas Kaleke Sigi",
        "ip_address": "175.10.1.3",
        "luno": "0159",
        "port": "8016",
        "vendor_name": "SRISHINDU",
        "serial_number": "J821004736",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 56,
        "profil": "NCR.SIGI",
        "cabang_kode": "007",
        "cabang_text": "007-Sigi",
        "urutan_cabang": 4,
        "nama_lokasi": "Kantor Bupati Sigi",
        "ip_address": "172.16.29.2",
        "luno": "0217",
        "port": "8092",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50737782",
        "denom": "50",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 57,
        "profil": "DBL.SIGI4",
        "cabang_kode": "007",
        "cabang_text": "007-Sigi",
        "urutan_cabang": 5,
        "nama_lokasi": "Kelapa Gading Sigi",
        "ip_address": "172.16.50.58",
        "luno": "0221",
        "port": "8246",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05376",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 58,
        "profil": "NCR.PALUBARAT",
        "cabang_kode": "008",
        "cabang_text": "008-Palu Barat",
        "urutan_cabang": 1,
        "nama_lokasi": "Galeri ATM Cabang Palu Barat",
        "ip_address": "192.168.227.130",
        "luno": "0095",
        "port": "8172",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50737785",
        "denom": "50",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 59,
        "profil": "WCR.PALBAR",
        "cabang_kode": "008",
        "cabang_text": "008-Palu Barat",
        "urutan_cabang": 2,
        "nama_lokasi": "Galeri ATM Swiss Bel Hotel",
        "ip_address": "175.12.43.2",
        "luno": "0209",
        "port": "8135",
        "vendor_name": "ASSINDO",
        "serial_number": "56HG701730",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 60,
        "profil": "DBL.MUSEUM1",
        "cabang_kode": "008",
        "cabang_text": "008-Palu Barat",
        "urutan_cabang": 3,
        "nama_lokasi": "Kantor Museum Palu",
        "ip_address": "172.16.45.2",
        "luno": "0128",
        "port": "8095",
        "vendor_name": "SRISHINDU",
        "serial_number": "FDC - 06731",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 61,
        "profil": "DBL.PALUBARAT",
        "cabang_kode": "008",
        "cabang_text": "008-Palu Barat",
        "urutan_cabang": 4,
        "nama_lokasi": "Galeri ATM Cabang Palu Barat",
        "ip_address": "175.10.3.254",
        "luno": "0138",
        "port": "8140",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 02144",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 62,
        "profil": "CRM.PALUBARAT",
        "cabang_kode": "008",
        "cabang_text": "008-Palu Barat",
        "urutan_cabang": 5,
        "nama_lokasi": "Galeri ATM Cabang Palu Barat",
        "ip_address": "172.16.45.3",
        "luno": "0180",
        "port": "8150",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0100",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 63,
        "profil": "DBL.SMART1",
        "cabang_kode": "008",
        "cabang_text": "008-Palu Barat",
        "urutan_cabang": 6,
        "nama_lokasi": "Swalayan Smart Kitchen",
        "ip_address": "175.12.19.3",
        "luno": "0139",
        "port": "8137",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06750",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 64,
        "profil": "DBL.JAKARTA",
        "cabang_kode": "009",
        "cabang_text": "009-Jakarta",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM Kantor Cabang Jakarta",
        "ip_address": "175.12.21.3",
        "luno": "0177",
        "port": "8151",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 04217",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 65,
        "profil": "DBL.DGL3",
        "cabang_kode": "101",
        "cabang_text": "101-Donggala",
        "urutan_cabang": 1,
        "nama_lokasi": "SPBU Donggala",
        "ip_address": "172.16.50.22",
        "luno": "0064",
        "port": "8064",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06736",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 66,
        "profil": "CRM.DONGGALA",
        "cabang_kode": "101",
        "cabang_text": "101-Donggala",
        "urutan_cabang": 2,
        "nama_lokasi": "Galeri ATM Cabang Donggala",
        "ip_address": "172.16.12.2",
        "luno": "0181",
        "port": "8031",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0097",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 67,
        "profil": "YHU.DGL2",
        "cabang_kode": "101",
        "cabang_text": "101-Donggala",
        "urutan_cabang": 3,
        "nama_lokasi": "Galeri ATM Cabang Donggala",
        "ip_address": "172.16.12.3",
        "luno": "0228",
        "port": "8253",
        "vendor_name": "ASSINDO",
        "serial_number": "H2410D00137",
        "denom": "100",
        "tipe_mesin": "YIHUA ATM",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 68,
        "profil": "DBL.PRGI",
        "cabang_kode": "102",
        "cabang_text": "102-Parigi",
        "urutan_cabang": 1,
        "nama_lokasi": "Alfamidi Toboli",
        "ip_address": "192.168.227.58",
        "luno": "0006",
        "port": "8090",
        "vendor_name": "HIBAH",
        "serial_number": "1522FDC26650",
        "denom": "50",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 69,
        "profil": "CRM.PARIGI",
        "cabang_kode": "102",
        "cabang_text": "102-Parigi",
        "urutan_cabang": 2,
        "nama_lokasi": "Galeri ATM Kantor cabang Parigi",
        "ip_address": "175.12.4.2",
        "luno": "0182",
        "port": "8035",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0094",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 70,
        "profil": "WCR.KCPARIGI",
        "cabang_kode": "102",
        "cabang_text": "102-Parigi",
        "urutan_cabang": 3,
        "nama_lokasi": "Galeri ATM Kantor cabang Parigi",
        "ip_address": "172.16.38.2",
        "luno": "0107",
        "port": "8054",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG701733",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 71,
        "profil": "DBL.PRG2",
        "cabang_kode": "102",
        "cabang_text": "102-Parigi",
        "urutan_cabang": 4,
        "nama_lokasi": "Gardu ATM RS Anuntaloko",
        "ip_address": "192.168.225.132",
        "luno": "0035",
        "port": "8006",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05380",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 72,
        "profil": "DBL.PRG3",
        "cabang_kode": "102",
        "cabang_text": "102-Parigi",
        "urutan_cabang": 5,
        "nama_lokasi": "Lobi Kantor Bupati Parigi",
        "ip_address": "172.16.13.2",
        "luno": "0054",
        "port": "8112",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06722",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 73,
        "profil": "WCR.PRGI",
        "cabang_kode": "102",
        "cabang_text": "102-Parigi",
        "urutan_cabang": 6,
        "nama_lokasi": "Alfamidi Parigi",
        "ip_address": "192.168.225.133",
        "luno": "0161",
        "port": "8175",
        "vendor_name": "SRISHINDU",
        "serial_number": "J821004733",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 74,
        "profil": "NCR.LAMBUNU",
        "cabang_kode": "103",
        "cabang_text": "103-Lambunu",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM KCP Lambunu",
        "ip_address": "175.11.5.2",
        "luno": "0093",
        "port": "8093",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 49254672",
        "denom": "50",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 75,
        "profil": "NCR.LABEAN",
        "cabang_kode": "104",
        "cabang_text": "104-KCP Labean",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM KCP Labean",
        "ip_address": "175.11.13.2",
        "luno": "0091",
        "port": "8091",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50738664",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 76,
        "profil": "WCR.SIOYONG",
        "cabang_kode": "104",
        "cabang_text": "104-KCP Labean",
        "urutan_cabang": 2,
        "nama_lokasi": "Alfamidi Sioyong Labean",
        "ip_address": "192.168.227.106",
        "luno": "0156",
        "port": "8169",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG8000252",
        "denom": "50",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 77,
        "profil": "DBL.KASTOLAI",
        "cabang_kode": "105",
        "cabang_text": "105-Tolai",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM KCP Tolai",
        "ip_address": "172.16.55.210",
        "luno": "0097",
        "port": "8102",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06718",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 78,
        "profil": "NCR.TINOMBO",
        "cabang_kode": "106",
        "cabang_text": "106-Tinombo",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM KCP Tinombo",
        "ip_address": "172.16.51.3",
        "luno": "0144",
        "port": "8156",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50738657",
        "denom": "50",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 79,
        "profil": "NCR.TINOMBALA1",
        "cabang_kode": "107",
        "cabang_text": "107-Tinombala",
        "urutan_cabang": 1,
        "nama_lokasi": "Gedung Workshop Bank Sulteng",
        "ip_address": "172.16.49.2",
        "luno": "0220",
        "port": "8245",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 211722",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 80,
        "profil": "DBL.KOTARAYA",
        "cabang_kode": "108",
        "cabang_text": "108-Kotaraya",
        "urutan_cabang": 1,
        "nama_lokasi": "KCP Kotaraya",
        "ip_address": "172.16.54.2",
        "luno": "0235",
        "port": "8261",
        "vendor_name": "HIBAH",
        "serial_number": "1522FDC26653",
        "denom": "100",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 81,
        "profil": "CRM.BUOL",
        "cabang_kode": "201",
        "cabang_text": "201-Buol",
        "urutan_cabang": 1,
        "nama_lokasi": "Galeri ATM Kantor Cabang Buol",
        "ip_address": "172.16.15.2",
        "luno": "0192",
        "port": "8138",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0093",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 82,
        "profil": "WCR.BUOL2",
        "cabang_kode": "201",
        "cabang_text": "201-Buol",
        "urutan_cabang": 2,
        "nama_lokasi": "Gardu ATM SPBU",
        "ip_address": "175.12.3.2",
        "luno": "0024",
        "port": "8024",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG701738",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 83,
        "profil": "DBL.BUO3",
        "cabang_kode": "201",
        "cabang_text": "201-Buol",
        "urutan_cabang": 3,
        "nama_lokasi": "Galeri ATM RSUD",
        "ip_address": "192.168.227.22",
        "luno": "0062",
        "port": "8062",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06738",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 84,
        "profil": "DBL.BUO4",
        "cabang_kode": "201",
        "cabang_text": "201-Buol",
        "urutan_cabang": 4,
        "nama_lokasi": "Gardu ATM Kantor PU",
        "ip_address": "192.168.227.26",
        "luno": "0074",
        "port": "8074",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06763",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 85,
        "profil": "NCR.BUOL5",
        "cabang_kode": "201",
        "cabang_text": "201-Buol",
        "urutan_cabang": 5,
        "nama_lokasi": "Galeri ATM Kantor keuangan",
        "ip_address": "175.12.25.2",
        "luno": "0086",
        "port": "8086",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50738654",
        "denom": "50",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 86,
        "profil": "WCR.BUOL",
        "cabang_kode": "201",
        "cabang_text": "201-Buol",
        "urutan_cabang": 6,
        "nama_lokasi": "Galeri ATM Kantor Cabang Buol",
        "ip_address": "192.168.229.3",
        "luno": "0158",
        "port": "8171",
        "vendor_name": "SRISHINDU",
        "serial_number": "J821004731",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 87,
        "profil": "YHU.BUOL7",
        "cabang_kode": "201",
        "cabang_text": "201-Buol",
        "urutan_cabang": 7,
        "nama_lokasi": "Galeri ATM Kantor Cabang Buol",
        "ip_address": "192.168.229.40",
        "luno": "0231",
        "port": "8256",
        "vendor_name": "ASSINDO",
        "serial_number": "H2410D00128",
        "denom": "100",
        "tipe_mesin": "YIHUA ATM",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 88,
        "profil": "WCR.SONI",
        "cabang_kode": "202",
        "cabang_text": "202-Soni",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM KCP Soni",
        "ip_address": "192.168.229.34",
        "luno": "0211",
        "port": "8004",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG701736",
        "denom": "50",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 89,
        "profil": "DBL.PLEH",
        "cabang_kode": "211",
        "cabang_text": "211-Paleleh",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM KCP Paleleh",
        "ip_address": "172.16.24.2",
        "luno": "0034",
        "port": "8034",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05382",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 90,
        "profil": "DBL.TOJO",
        "cabang_kode": "301",
        "cabang_text": "301-Ampana",
        "urutan_cabang": 1,
        "nama_lokasi": "Alfamidi Tayawa Ampana",
        "ip_address": "172.16.42.2",
        "luno": "0101",
        "port": null,
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06737",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 91,
        "profil": "DBL.AMP",
        "cabang_kode": "301",
        "cabang_text": "301-Ampana",
        "urutan_cabang": 2,
        "nama_lokasi": "Indomaret Ampana",
        "ip_address": "172.16.50.82",
        "luno": "0021",
        "port": "8021",
        "vendor_name": "ASSINDO",
        "serial_number": null,
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 92,
        "profil": "DBL.AMP3",
        "cabang_kode": "301",
        "cabang_text": "301-Ampana",
        "urutan_cabang": 3,
        "nama_lokasi": "Galeri ATM Swalayan Maraja Mart",
        "ip_address": "192.168.225.178",
        "luno": "0058",
        "port": "8057",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06745",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 93,
        "profil": "DBL.AMP5",
        "cabang_kode": "301",
        "cabang_text": "301-Ampana",
        "urutan_cabang": 4,
        "nama_lokasi": "Gardu ATM Kantor Bupati Ampana",
        "ip_address": "172.16.50.26",
        "luno": "0167",
        "port": "8058",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05374",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 94,
        "profil": "DBL.AMP2",
        "cabang_kode": "301",
        "cabang_text": "301-Ampana",
        "urutan_cabang": 5,
        "nama_lokasi": "Galeri ATM Kantor Cabang Ampana 50k",
        "ip_address": "172.16.22.2",
        "luno": "0057",
        "port": "8181",
        "vendor_name": "HIBAH",
        "serial_number": "1522FDC13567",
        "denom": "50",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 95,
        "profil": "CRM.AMPANA",
        "cabang_kode": "301",
        "cabang_text": "301-Ampana",
        "urutan_cabang": 6,
        "nama_lokasi": "Galeri ATM Kantor Cabang Ampana",
        "ip_address": "192.168.227.70",
        "luno": "0184",
        "port": "8106",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0092",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 96,
        "profil": "WCR.AMP1",
        "cabang_kode": "301",
        "cabang_text": "301-Ampana",
        "urutan_cabang": 7,
        "nama_lokasi": "Galeri ATM Kantor Cabang Ampana 100k",
        "ip_address": "175.12.35.2",
        "luno": "0166",
        "port": "8130",
        "vendor_name": "SRISHINDU",
        "serial_number": "J821004737",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 97,
        "profil": "YHU.AMP4",
        "cabang_kode": "301",
        "cabang_text": "301-Ampana",
        "urutan_cabang": 8,
        "nama_lokasi": "Galeri ATM Kantor Cabang Ampana",
        "ip_address": null,
        "luno": "0227",
        "port": "8252",
        "vendor_name": "ASSINDO",
        "serial_number": "H2410D00129",
        "denom": "100",
        "tipe_mesin": "YIHUA ATM",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 98,
        "profil": "DBL.WAKAI2",
        "cabang_kode": "302",
        "cabang_text": "302-Wakai",
        "urutan_cabang": 7,
        "nama_lokasi": "Kantor Kas Wakai",
        "ip_address": "172.16.22.253",
        "luno": "0198",
        "port": "8180",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06721",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 99,
        "profil": "DBL.TTNA",
        "cabang_kode": "303",
        "cabang_text": "303-Tentena",
        "urutan_cabang": 1,
        "nama_lokasi": "KCP TENTENA",
        "ip_address": "175.11.1.2",
        "luno": "0056",
        "port": "8124",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06728",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 100,
        "profil": "YHU.TTNA2",
        "cabang_kode": "303",
        "cabang_text": "303-Tentena",
        "urutan_cabang": 1,
        "nama_lokasi": "KCP TENTENA",
        "ip_address": "172.16.43.4",
        "luno": "0232",
        "port": "8257",
        "vendor_name": "ASSINDO",
        "serial_number": "H2410D00135",
        "denom": "100",
        "tipe_mesin": "YIHUA ATM",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 101,
        "profil": "DBL.PENDOLO1",
        "cabang_kode": "304",
        "cabang_text": "304-Pendolo",
        "urutan_cabang": 1,
        "nama_lokasi": "KCP PENDOLO",
        "ip_address": "172.16.43.2",
        "luno": "0175",
        "port": "8056",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06752",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 102,
        "profil": "DBL.NAPU",
        "cabang_kode": "305",
        "cabang_text": "305-Napu",
        "urutan_cabang": 1,
        "nama_lokasi": "KCP NAPU",
        "ip_address": "175.10.14.3",
        "luno": "0219",
        "port": "8189",
        "vendor_name": "HIBAH",
        "serial_number": "1522FDC25162",
        "denom": "50",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 103,
        "profil": "DBL.TAMBARANA1",
        "cabang_kode": "306",
        "cabang_text": "306-Tambarana",
        "urutan_cabang": 1,
        "nama_lokasi": "KCP TAMBARANA",
        "ip_address": "172.16.53.2",
        "luno": "0234",
        "port": "8259",
        "vendor_name": "HIBAH",
        "serial_number": "1522FDC26649",
        "denom": "50",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 104,
        "profil": "DBL.MOR2",
        "cabang_kode": "401",
        "cabang_text": "401-Kolonodale",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM RSUD Kolonodale",
        "ip_address": "192.168.225.150",
        "luno": "0049",
        "port": "8049",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05375",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 105,
        "profil": "WCR.MORO2",
        "cabang_kode": "401",
        "cabang_text": "401-Kolonodale",
        "urutan_cabang": 2,
        "nama_lokasi": "Kantor Cabang Kolonodale",
        "ip_address": "192.168.225.150",
        "luno": "0155",
        "port": "8120",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG800344",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 106,
        "profil": "CRM.KOLONODALE",
        "cabang_kode": "401",
        "cabang_text": "401-Kolonodale",
        "urutan_cabang": 3,
        "nama_lokasi": "Kantor Cabang Kolonodale",
        "ip_address": "172.16.20.2",
        "luno": "0189",
        "port": "8168",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0101",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 107,
        "profil": "YHU.KODAL4",
        "cabang_kode": "401",
        "cabang_text": "401-Kolonodale",
        "urutan_cabang": 4,
        "nama_lokasi": "KANTOR CABANG KOLONODALE",
        "ip_address": "192.168.225.150",
        "luno": "0225",
        "port": "8250",
        "vendor_name": "ASSINDO",
        "serial_number": "H2410D00130",
        "denom": "100",
        "tipe_mesin": "YIHUA ATM",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 108,
        "profil": "YHU.KODAL5",
        "cabang_kode": "401",
        "cabang_text": "401-Kolonodale",
        "urutan_cabang": 5,
        "nama_lokasi": "KANTOR BUPATI KOLONODALE",
        "ip_address": "172.16.50.74",
        "luno": "0226",
        "port": "8251",
        "vendor_name": "ASSINDO",
        "serial_number": "H2410D00134",
        "denom": "100",
        "tipe_mesin": "YIHUA ATM",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 109,
        "profil": "DBL.BALUT3",
        "cabang_kode": "402",
        "cabang_text": "402-Banggai Laut",
        "urutan_cabang": 1,
        "nama_lokasi": "Balaikota Banggai Laut",
        "ip_address": "172.16.39.3",
        "luno": "0203",
        "port": "8188",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 05376",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 110,
        "profil": "DBL.BALUT4",
        "cabang_kode": "402",
        "cabang_text": "402-Banggai Laut",
        "urutan_cabang": 2,
        "nama_lokasi": "Galeri ATM Kantor Cabang Banggai Laut",
        "ip_address": "172.16.39.5",
        "luno": "0238",
        "port": "8291",
        "vendor_name": "HIBAH",
        "serial_number": "1522FDC09152",
        "denom": "100",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 111,
        "profil": "NCR.BALUT",
        "cabang_kode": "402",
        "cabang_text": "402-Banggai Laut",
        "urutan_cabang": 3,
        "nama_lokasi": "Gardu ATM RSUD",
        "ip_address": "192.168.227.50",
        "luno": "0085",
        "port": "8085",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50737777",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 112,
        "profil": "DBL.BALUT2",
        "cabang_kode": "402",
        "cabang_text": "402-Banggai Laut",
        "urutan_cabang": 4,
        "nama_lokasi": "Galeri ATM Kantor Cabang Banggai Laut",
        "ip_address": "175.10.13.4",
        "luno": "0201",
        "port": "8121",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 02016",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 113,
        "profil": "CRM.BALUT",
        "cabang_kode": "402",
        "cabang_text": "402-Banggai Laut",
        "urutan_cabang": 5,
        "nama_lokasi": "Galeri ATM Kantor Cabang Banggai Laut",
        "ip_address": "192.168.228.30",
        "luno": "0186",
        "port": "8097",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0095",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 114,
        "profil": "DBL.BETELEME",
        "cabang_kode": "403",
        "cabang_text": "403-Beteleme",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM KCP Beteleme",
        "ip_address": "172.16.55.162",
        "luno": "0059",
        "port": "8053",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06754",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 115,
        "profil": "DBL.KASBATUI",
        "cabang_kode": "404",
        "cabang_text": "404-Batui",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM Kas Batui",
        "ip_address": "175.10.4.2",
        "luno": "0102",
        "port": "8108",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06723",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 116,
        "profil": "WCR.TOILI",
        "cabang_kode": "405",
        "cabang_text": "405-Toili",
        "urutan_cabang": 2,
        "nama_lokasi": "Gardu ATM KCP Toili",
        "ip_address": "192.168.227.122",
        "luno": "0103",
        "port": "8179",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG701729",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 117,
        "profil": "WCR.TOILI2",
        "cabang_kode": "405",
        "cabang_text": "405-Toili",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM Pasar Toili Barat",
        "ip_address": "192.168.228.90",
        "luno": "0165",
        "port": "8174",
        "vendor_name": "SRISHINDU",
        "serial_number": "J821004734",
        "denom": "50",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 118,
        "profil": "DBL.MASAMA",
        "cabang_kode": "406",
        "cabang_text": "406-Masama",
        "urutan_cabang": 1,
        "nama_lokasi": "KCP Masama",
        "ip_address": "175.10.16.3",
        "luno": "0236",
        "port": "8262",
        "vendor_name": "HIBAH",
        "serial_number": "1522FDC09155",
        "denom": "100",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 119,
        "profil": "DBL.BUNTA01",
        "cabang_kode": "407",
        "cabang_text": "407-Bunta",
        "urutan_cabang": 1,
        "nama_lokasi": "KCP Bunta",
        "ip_address": "172.16.56.3",
        "luno": "0237",
        "port": "8290",
        "vendor_name": "HIBAH",
        "serial_number": "1522FDC13574",
        "denom": "100",
        "tipe_mesin": "Diebold 522",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 120,
        "profil": "WCR.MAMOSALATO",
        "cabang_kode": "411",
        "cabang_text": "411-Mamosalato",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM KCP Mamosalato",
        "ip_address": "175.11.6.2",
        "luno": "0160",
        "port": "8126",
        "vendor_name": "SRISHINDU",
        "serial_number": "J821004738",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 121,
        "profil": "WCR.TOMATA",
        "cabang_kode": "412",
        "cabang_text": "412-Tomata",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM KCP Tomata",
        "ip_address": "175.11.9.2",
        "luno": "0208",
        "port": "8147",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG701735",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 122,
        "profil": "NCR.BATURUBE",
        "cabang_kode": "413",
        "cabang_text": "413-Baturube",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM KCP Baturube",
        "ip_address": "175.11.4.6",
        "luno": "0135",
        "port": "8142",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 96428718",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 123,
        "profil": "DBL.BHMTF1",
        "cabang_kode": "501",
        "cabang_text": "501-Bahomotefe",
        "urutan_cabang": 1,
        "nama_lokasi": "Galeri ATM KCP Bahometefe",
        "ip_address": "175.10.8.8",
        "luno": "0194",
        "port": "8158",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06740",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 124,
        "profil": "DBL.BHMTF2",
        "cabang_kode": "501",
        "cabang_text": "501-Bahomotefe",
        "urutan_cabang": 2,
        "nama_lokasi": "Galeri ATM KCP Bahometefe",
        "ip_address": "175.10.8.10",
        "luno": "0202",
        "port": "8161",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 08461",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 125,
        "profil": "NCR.BHDP1",
        "cabang_kode": "502",
        "cabang_text": "502-Bahodopi",
        "urutan_cabang": 1,
        "nama_lokasi": "Galeri ATM Capem Bahodopi",
        "ip_address": "192.168.229.22",
        "luno": "0146",
        "port": "8162",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 96428717",
        "denom": "50",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 126,
        "profil": "NCR.BHDP2",
        "cabang_kode": "502",
        "cabang_text": "502-Bahodopi",
        "urutan_cabang": 2,
        "nama_lokasi": "Galeri ATM Capem Bahodopi",
        "ip_address": "192.168.229.23",
        "luno": "0148",
        "port": "8163",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 96428712",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 127,
        "profil": "NCR.BHDP3",
        "cabang_kode": "502",
        "cabang_text": "502-Bahodopi",
        "urutan_cabang": 3,
        "nama_lokasi": "Galeri ATM Qarim Labota",
        "ip_address": "175.10.8.9",
        "luno": "0149",
        "port": "8159",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 96428716",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 128,
        "profil": "NCR.BHDP4",
        "cabang_kode": "502",
        "cabang_text": "502-Bahodopi",
        "urutan_cabang": 4,
        "nama_lokasi": "Galeri ATM Capem Bahodopi",
        "ip_address": "192.168.227.114",
        "luno": "0150",
        "port": "8167",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50738650",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 129,
        "profil": "DBL.BHDP",
        "cabang_kode": "502",
        "cabang_text": "502-Bahodopi",
        "urutan_cabang": 5,
        "nama_lokasi": "Galeri ATM Capem Bahodopi",
        "ip_address": "175.12.36.4",
        "luno": "0147",
        "port": "8164",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 08455",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 130,
        "profil": "DBL.BHDP2",
        "cabang_kode": "502",
        "cabang_text": "502-Bahodopi",
        "urutan_cabang": 6,
        "nama_lokasi": "Galeri ATM Rusunawa",
        "ip_address": "192.168.225.228",
        "luno": "0154",
        "port": "8165",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06746",
        "denom": "100",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 131,
        "profil": "CRM.BAHODOPI",
        "cabang_kode": "502",
        "cabang_text": "502-Bahodopi",
        "urutan_cabang": 7,
        "nama_lokasi": "Galeri ATM Capem Bahodopi",
        "ip_address": "172.16.55.131",
        "luno": "0190",
        "port": "8134",
        "vendor_name": "ASSINDO",
        "serial_number": "B2209D0102",
        "denom": "50/100",
        "tipe_mesin": "YIHUA CRM",
        "kategori": "CRM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 132,
        "profil": "WCR.MBHDP",
        "cabang_kode": "502",
        "cabang_text": "502-Bahodopi",
        "urutan_cabang": 8,
        "nama_lokasi": "MOBIL ATM Bahodopi",
        "ip_address": "172.16.48.2",
        "luno": "0152",
        "port": "8122",
        "vendor_name": "HIBAH SRISHINDU",
        "serial_number": "56HG701742",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": true,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 133,
        "profil": "WCR.BHDP2",
        "cabang_kode": "502",
        "cabang_text": "502-Bahodopi",
        "urutan_cabang": 9,
        "nama_lokasi": "Bungku Pesisir",
        "ip_address": "175.12.26.3",
        "luno": "0218",
        "port": "8133",
        "vendor_name": "SRISHINDU",
        "serial_number": "56HG701739",
        "denom": "100",
        "tipe_mesin": "Wincor 280",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 134,
        "profil": "DBL.KULAWI",
        "cabang_kode": "701",
        "cabang_text": "701-Kulawi",
        "urutan_cabang": 1,
        "nama_lokasi": "Kantor Kas Kulawi",
        "ip_address": "175.10.11.3",
        "luno": "0207",
        "port": "8192",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 00787",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 135,
        "profil": "NCR.TAWAELI",
        "cabang_kode": "801",
        "cabang_text": "801-Capem Tawaeli",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM Capem Tawaeli",
        "ip_address": "175.10.11.3",
        "luno": "0115",
        "port": "8192",
        "vendor_name": "ASSINDO",
        "serial_number": "94 - 50737780",
        "denom": "100",
        "tipe_mesin": "NCR SS22E",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    },
    {
        "no": 136,
        "profil": "DBL.TOAYA1",
        "cabang_kode": "801",
        "cabang_text": "801-Capem Tawaeli",
        "urutan_cabang": 1,
        "nama_lokasi": "Gardu ATM Kantor Camat Toaya",
        "ip_address": "175.10.11.3",
        "luno": "0126",
        "port": "8192",
        "vendor_name": "ASSINDO",
        "serial_number": "FDC - 06720",
        "denom": "50",
        "tipe_mesin": "Diebold 529",
        "kategori": "ATM",
        "is_hibah": false,
        "rek_ia": null,
        "status": "Aktif"
    }
]
JSON;

        foreach (json_decode($terminalsJson, true) as $item) {
            Terminal::updateOrCreate(
                ['profil' => $item['profil']],
                [
                    'cabang_id' => $cabangMap[$item['cabang_kode']] ?? null,
                    'cabang_text' => $item['cabang_text'],
                    'urutan_cabang' => $item['urutan_cabang'],
                    'nama_lokasi' => $item['nama_lokasi'],
                    'ip_address' => $item['ip_address'],
                    'luno' => $item['luno'],
                    'port' => $item['port'],
                    'vendor_id' => $vendorMap[$item['vendor_name']] ?? null,
                    'vendor_text' => $item['vendor_name'],
                    'serial_number' => $item['serial_number'],
                    'denom' => $item['denom'],
                    'tipe_mesin' => $item['tipe_mesin'],
                    'kategori' => $item['kategori'],
                    'is_hibah' => $item['is_hibah'],
                    'rek_ia' => $item['rek_ia'],
                    'status' => $item['status'],
                ]
            );
        }
    }
}
