<?php

namespace Database\Seeders;

use App\Models\Cabang;
use App\Models\Terminal;
use App\Models\Vendor;
use Illuminate\Database\Seeder;

class TerminalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Seed Vendors
        $vendorsJson = <<<'JSON'
[
    "ASSINDO",
    "HIBAH",
    "HIBAH SRISHINDU",
    "SRISHINDU",
    "SRISHINDU INFORMATIKA",
    "PT KIS",
    "KOPERASI BANK SULTENG",
    "COLLEGA INTI PRATAMA"
]
JSON;
        $vendorMap = [];
        foreach (json_decode($vendorsJson, true) as $vName) {
            $v = Vendor::firstOrCreate(['nama_vendor' => $vName]);
            $vendorMap[$vName] = $v->id;
        }

        // 2. Seed Cabang
        $cabangsJson = <<<'JSON'
[
    {
        "kode": "001",
        "nama": "Utama Palu",
        "label": "001-Utama Palu",
        "urutan": 1
    },
    {
        "kode": "002",
        "nama": "Toli-Toli",
        "label": "002-Toli-Toli",
        "urutan": 2
    },
    {
        "kode": "003",
        "nama": "Poso",
        "label": "003-Poso",
        "urutan": 3
    },
    {
        "kode": "004",
        "nama": "Luwuk",
        "label": "004-Luwuk",
        "urutan": 4
    },
    {
        "kode": "005",
        "nama": "Bungku",
        "label": "005-Bungku",
        "urutan": 5
    },
    {
        "kode": "006",
        "nama": "Salakan",
        "label": "006-Salakan",
        "urutan": 6
    },
    {
        "kode": "007",
        "nama": "Sigi",
        "label": "007-Sigi",
        "urutan": 7
    },
    {
        "kode": "008",
        "nama": "Palu Barat",
        "label": "008-Palu Barat",
        "urutan": 8
    },
    {
        "kode": "009",
        "nama": "Jakarta",
        "label": "009-Jakarta",
        "urutan": 9
    },
    {
        "kode": "101",
        "nama": "Donggala",
        "label": "101-Donggala",
        "urutan": 10
    },
    {
        "kode": "102",
        "nama": "Parigi",
        "label": "102-Parigi",
        "urutan": 11
    },
    {
        "kode": "103",
        "nama": "Lambunu",
        "label": "103-Lambunu",
        "urutan": 12
    },
    {
        "kode": "104",
        "nama": "KCP Labean",
        "label": "104-KCP Labean",
        "urutan": 13
    },
    {
        "kode": "105",
        "nama": "Tolai",
        "label": "105-Tolai",
        "urutan": 14
    },
    {
        "kode": "106",
        "nama": "Tinombo",
        "label": "106-Tinombo",
        "urutan": 15
    },
    {
        "kode": "107",
        "nama": "Tinombala",
        "label": "107-Tinombala",
        "urutan": 16
    },
    {
        "kode": "108",
        "nama": "Kotaraya",
        "label": "108-Kotaraya",
        "urutan": 17
    },
    {
        "kode": "201",
        "nama": "Buol",
        "label": "201-Buol",
        "urutan": 18
    },
    {
        "kode": "202",
        "nama": "Soni",
        "label": "202-Soni",
        "urutan": 19
    },
    {
        "kode": "211",
        "nama": "Paleleh",
        "label": "211-Paleleh",
        "urutan": 20
    },
    {
        "kode": "301",
        "nama": "Ampana",
        "label": "301-Ampana",
        "urutan": 21
    },
    {
        "kode": "302",
        "nama": "Wakai",
        "label": "302-Wakai",
        "urutan": 22
    },
    {
        "kode": "303",
        "nama": "Tentena",
        "label": "303-Tentena",
        "urutan": 23
    },
    {
        "kode": "304",
        "nama": "Pendolo",
        "label": "304-Pendolo",
        "urutan": 24
    },
    {
        "kode": "305",
        "nama": "Napu",
        "label": "305-Napu",
        "urutan": 25
    },
    {
        "kode": "306",
        "nama": "Tambarana",
        "label": "306-Tambarana",
        "urutan": 26
    },
    {
        "kode": "401",
        "nama": "Kolonodale",
        "label": "401-Kolonodale",
        "urutan": 27
    },
    {
        "kode": "402",
        "nama": "Banggai Laut",
        "label": "402-Banggai Laut",
        "urutan": 28
    },
    {
        "kode": "403",
        "nama": "Beteleme",
        "label": "403-Beteleme",
        "urutan": 29
    },
    {
        "kode": "404",
        "nama": "Batui",
        "label": "404-Batui",
        "urutan": 30
    },
    {
        "kode": "405",
        "nama": "Toili",
        "label": "405-Toili",
        "urutan": 31
    },
    {
        "kode": "406",
        "nama": "Masama",
        "label": "406-Masama",
        "urutan": 32
    },
    {
        "kode": "407",
        "nama": "Bunta",
        "label": "407-Bunta",
        "urutan": 33
    },
    {
        "kode": "411",
        "nama": "Mamosalato",
        "label": "411-Mamosalato",
        "urutan": 34
    },
    {
        "kode": "412",
        "nama": "Tomata",
        "label": "412-Tomata",
        "urutan": 35
    },
    {
        "kode": "413",
        "nama": "Baturube",
        "label": "413-Baturube",
        "urutan": 36
    },
    {
        "kode": "501",
        "nama": "Bahomotefe",
        "label": "501-Bahomotefe",
        "urutan": 37
    },
    {
        "kode": "502",
        "nama": "Bahodopi",
        "label": "502-Bahodopi",
        "urutan": 38
    },
    {
        "kode": "701",
        "nama": "Kulawi",
        "label": "701-Kulawi",
        "urutan": 39
    },
    {
        "kode": "801",
        "nama": "Capem Tawaeli",
        "label": "801-Capem Tawaeli",
        "urutan": 40
    }
]
JSON;
        $cabangMap = [];
        foreach (json_decode($cabangsJson, true) as $cData) {
            $c = Cabang::firstOrCreate(
                ['kode_cabang' => $cData['kode']],
                [
                    'nama_cabang' => $cData['nama'],
                    'label_cabang' => $cData['label'],
                    'urutan' => $cData['urutan'],
                ]
            );
            $cabangMap[$cData['kode']] = $c->id;
        }

        // 3. Seed Terminals (147 Units)
        $terminalsJson = <<<'JSON'
[
        {
            "no": 1,
            "profil": "WCR.KCU1",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 1,
            "nama_lokasi": "RS Undata Palu",
            "ip_address": "175.12.41.2",
            "luno": "0200",
            "port": "8220",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701702",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 2,
            "profil": "GRG.KCU10",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 2,
            "nama_lokasi": "Grand Hero",
            "ip_address": "172.16.33.2",
            "luno": "0448",
            "port": "8318",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 3,
            "profil": "DBL.GBNR",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 3,
            "nama_lokasi": "Kantor Gubernur",
            "ip_address": "172.16.30.2",
            "luno": "0002",
            "port": "8002",
            "vendor_name": "ASSINDO",
            "serial_number": "1529FDC06730",
            "denom": "100",
            "tipe_mesin": "ATM Diebold OPTEVA 529",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 4,
            "profil": "DBL.SAMS",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 4,
            "nama_lokasi": "Kantor Samsat",
            "ip_address": "172.16.27.2",
            "luno": "0018",
            "port": "8018",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "1522FDC20645",
            "denom": "100",
            "tipe_mesin": "ATM Diebold OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 5,
            "profil": "GRG.KCU7",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 5,
            "nama_lokasi": "Alfamidi Destik",
            "ip_address": "175.12.17.2",
            "luno": "0445",
            "port": "8315",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 6,
            "profil": "GRG.KCU11",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 6,
            "nama_lokasi": "Gatsumaya ( MRAYA )",
            "ip_address": "172.16.50.2",
            "luno": "0449",
            "port": "8319",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 7,
            "profil": "GRG.KCU13",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 7,
            "nama_lokasi": "Bappeda Propinsi Palu",
            "ip_address": "175.12.8.2",
            "luno": "0454",
            "port": "8324",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 8,
            "profil": "GRG.KCU8",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 8,
            "nama_lokasi": "Dinkes Sulteng",
            "ip_address": "175.12.9.2",
            "luno": "0446",
            "port": "8316",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 9,
            "profil": "GRG.KCU14",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 9,
            "nama_lokasi": "Dikjar Sulteng",
            "ip_address": "175.12.11.2",
            "luno": "0455",
            "port": "8325",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 10,
            "profil": "DBL.BKD",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 10,
            "nama_lokasi": "BKD Sulteng",
            "ip_address": "175.12.10.3",
            "luno": "0072",
            "port": "8143",
            "vendor_name": "ASSINDO",
            "serial_number": "1529FDC06733",
            "denom": "100",
            "tipe_mesin": "ATM Diebold OPTEVA 529",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 11,
            "profil": "GRG.KCU12",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 11,
            "nama_lokasi": "Alfamidi Veteran Palu",
            "ip_address": "172.16.55.2",
            "luno": "0450",
            "port": "8320",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 12,
            "profil": "GRG.KCU15",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 12,
            "nama_lokasi": "Deperindakop ( BNS )",
            "ip_address": "175.12.12.2",
            "luno": "0456",
            "port": "8326",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 13,
            "profil": "GRG.KCU2",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 13,
            "nama_lokasi": "Kantor Perizinan Palu",
            "ip_address": "172.16.50.38",
            "luno": "0441",
            "port": "8311",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 14,
            "profil": "GRG.KCU9",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 14,
            "nama_lokasi": "Alfamidi Touwa",
            "ip_address": "172.16.50.34",
            "luno": "0447",
            "port": "8317",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 15,
            "profil": "CRM.KCU1",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 15,
            "nama_lokasi": "Bapenda Palu",
            "ip_address": "172.16.50.126",
            "luno": "0176",
            "port": "8191",
            "vendor_name": "ASSINDO",
            "serial_number": "B2010D00482",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 16,
            "profil": "GRG.KCU1",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 16,
            "nama_lokasi": "Disabilitas cabang Utama",
            "ip_address": "10.10.10.22",
            "luno": "0425",
            "port": "8307",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 17,
            "profil": "CRM.KCU3",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 17,
            "nama_lokasi": "Digital Lounge Cabang Utama",
            "ip_address": "172.16.75.19",
            "luno": "0240",
            "port": "8292",
            "vendor_name": "COLLEGA INTI PRATAMA",
            "serial_number": null,
            "denom": "50/100",
            "tipe_mesin": "CRM HYOSUNG",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 18,
            "profil": "CRM.KCU4",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 18,
            "nama_lokasi": "Digital Lounge Cabang Utama",
            "ip_address": "172.16.75.18",
            "luno": "0241",
            "port": "8293",
            "vendor_name": "COLLEGA INTI PRATAMA",
            "serial_number": null,
            "denom": "50/100",
            "tipe_mesin": "CRM HYOSUNG",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 19,
            "profil": "CRM.KCU5",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 19,
            "nama_lokasi": "Digital Lounge Cabang Utama",
            "ip_address": "172.16.75.20",
            "luno": "0242",
            "port": "8294",
            "vendor_name": "COLLEGA INTI PRATAMA",
            "serial_number": null,
            "denom": "50/100",
            "tipe_mesin": "CRM HYOSUNG",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 20,
            "profil": "CRM.KCU6",
            "cabang_kode": "001",
            "cabang_text": "001-Utama Palu",
            "urutan_cabang": 20,
            "nama_lokasi": "Digital Lounge Cabang Utama",
            "ip_address": "172.16.75.21",
            "luno": "0243",
            "port": "8295",
            "vendor_name": "COLLEGA INTI PRATAMA",
            "serial_number": null,
            "denom": "50/100",
            "tipe_mesin": "CRM HYOSUNG",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 21,
            "profil": "DBL.TOL2",
            "cabang_kode": "002",
            "cabang_text": "002-Toli-Toli",
            "urutan_cabang": 1,
            "nama_lokasi": "Kantor Cabang Toli-toli",
            "ip_address": "172.16.14.6",
            "luno": "0023",
            "port": "8023",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": "1522FDC13572",
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 22,
            "profil": "GRG.TOL3",
            "cabang_kode": "002",
            "cabang_text": "002-Toli-Toli",
            "urutan_cabang": 2,
            "nama_lokasi": "Kantor Keuangan Toli-toli",
            "ip_address": "175.12.22.3",
            "luno": "0480",
            "port": "8350",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 23,
            "profil": "GRG.TOL4",
            "cabang_kode": "002",
            "cabang_text": "002-Toli-Toli",
            "urutan_cabang": 3,
            "nama_lokasi": "Kantor Cabang Toli-toli",
            "ip_address": "192.168.225.73",
            "luno": "0481",
            "port": "8351",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 24,
            "profil": "WCR.TOL5",
            "cabang_kode": "002",
            "cabang_text": "002-Toli-Toli",
            "urutan_cabang": 4,
            "nama_lokasi": "Alfamidi Nopi Toli-toli",
            "ip_address": "175.12.39.2",
            "luno": "0164",
            "port": "8178",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "J821004735",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 25,
            "profil": "YHU.TOL6",
            "cabang_kode": "002",
            "cabang_text": "002-Toli-Toli",
            "urutan_cabang": 5,
            "nama_lokasi": "Kantor Cabang Toli-toli",
            "ip_address": "172.16.14.7",
            "luno": "0224",
            "port": "8249",
            "vendor_name": "ASSINDO",
            "serial_number": "H2410D00132",
            "denom": "100",
            "tipe_mesin": "ATM YIHUA",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 26,
            "profil": "DBL.TOL8",
            "cabang_kode": "002",
            "cabang_text": "002-Toli-Toli",
            "urutan_cabang": 6,
            "nama_lokasi": "Kantor Cabang Toli-toli",
            "ip_address": "172.16.14.5",
            "luno": "0434",
            "port": "8306",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 27,
            "profil": "CRM.TOLIS1",
            "cabang_kode": "002",
            "cabang_text": "002-Toli-Toli",
            "urutan_cabang": 7,
            "nama_lokasi": "Kantor Cabang Toli-toli",
            "ip_address": "172.16.14.3",
            "luno": "0195",
            "port": "8213",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0090",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 28,
            "profil": "CRM.TOLIS2",
            "cabang_kode": "002",
            "cabang_text": "002-Toli-Toli",
            "urutan_cabang": 8,
            "nama_lokasi": "Alfamidi Sandana",
            "ip_address": "172.16.50.122",
            "luno": "0433",
            "port": "8305",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0089",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 29,
            "profil": "GRG.POSO2",
            "cabang_kode": "003",
            "cabang_text": "003-Poso",
            "urutan_cabang": 1,
            "nama_lokasi": "Gardu ATM Pasar Kasiguncu",
            "ip_address": "175.12.38.2",
            "luno": "0457",
            "port": "8327",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 30,
            "profil": "GRG.POSO10",
            "cabang_kode": "003",
            "cabang_text": "003-Poso",
            "urutan_cabang": 2,
            "nama_lokasi": "Gardu ATM Kantor Bupati Poso",
            "ip_address": "172.16.50.50",
            "luno": "0458",
            "port": "8328",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 31,
            "profil": "GRG.POSO3",
            "cabang_kode": "003",
            "cabang_text": "003-Poso",
            "urutan_cabang": 3,
            "nama_lokasi": "Galeri ATM Kantor Cabang Poso",
            "ip_address": "172.16.16.101",
            "luno": "0452",
            "port": "8322",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 32,
            "profil": "GRG.POSO4",
            "cabang_kode": "003",
            "cabang_text": "003-Poso",
            "urutan_cabang": 4,
            "nama_lokasi": "Galeri ATM Kantor Cabang Poso",
            "ip_address": "192.168.225.84",
            "luno": "0464",
            "port": "8334",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 33,
            "profil": "GRG.POSO5",
            "cabang_kode": "003",
            "cabang_text": "003-Poso",
            "urutan_cabang": 5,
            "nama_lokasi": "Galeri ATM Kantor Cabang Poso",
            "ip_address": "192.168.225.85",
            "luno": "0465",
            "port": "8335",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 34,
            "profil": "GRG.POSO6",
            "cabang_kode": "003",
            "cabang_text": "003-Poso",
            "urutan_cabang": 6,
            "nama_lokasi": "Gardu ATM Kantor Bupati Poso",
            "ip_address": "172.16.50.51",
            "luno": "0453",
            "port": "8323",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 35,
            "profil": "GRG.POSO7",
            "cabang_kode": "003",
            "cabang_text": "003-Poso",
            "urutan_cabang": 7,
            "nama_lokasi": "Galeri ATM Kantor Cabang Poso",
            "ip_address": "172.16.16.105",
            "luno": "0466",
            "port": "8336",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 36,
            "profil": "WCR.POSO8",
            "cabang_kode": "003",
            "cabang_text": "003-Poso",
            "urutan_cabang": 8,
            "nama_lokasi": "Gardu ATM Denzipur Poso",
            "ip_address": "192.168.227.38",
            "luno": "0214",
            "port": "8239",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701709",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 37,
            "profil": "GRG.POSO9",
            "cabang_kode": "003",
            "cabang_text": "003-Poso",
            "urutan_cabang": 9,
            "nama_lokasi": "Gardu ATM RSUD Poso",
            "ip_address": "172.16.55.180",
            "luno": "0459",
            "port": "8329",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 38,
            "profil": "CRM.POSO",
            "cabang_kode": "003",
            "cabang_text": "003-Poso",
            "urutan_cabang": 10,
            "nama_lokasi": "Galeri ATM Kantor Cabang Poso",
            "ip_address": "172.16.16.106",
            "luno": "0183",
            "port": "8205",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0103",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 39,
            "profil": "GRG.LUWUK4",
            "cabang_kode": "004",
            "cabang_text": "004-Luwuk",
            "urutan_cabang": 1,
            "nama_lokasi": "Kantor MPP Luwuk",
            "ip_address": "172.2.2.2",
            "luno": "0514",
            "port": "8384",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 40,
            "profil": "GRG.LUWUK2",
            "cabang_kode": "004",
            "cabang_text": "004-Luwuk",
            "urutan_cabang": 2,
            "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
            "ip_address": "172.16.75.39",
            "luno": "0513",
            "port": "8383",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 41,
            "profil": "GRG.LUWUK5",
            "cabang_kode": "004",
            "cabang_text": "004-Luwuk",
            "urutan_cabang": 3,
            "nama_lokasi": "Gardu ATM Kantor Bupati Luwuk",
            "ip_address": "172.16.32.2",
            "luno": "0515",
            "port": "8385",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 42,
            "profil": "CRM.LUWUK",
            "cabang_kode": "004",
            "cabang_text": "004-Luwuk",
            "urutan_cabang": 4,
            "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
            "ip_address": "172.16.17.6",
            "luno": "0185",
            "port": "8207",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0099",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 43,
            "profil": "DBL.LWK",
            "cabang_kode": "004",
            "cabang_text": "004-Luwuk",
            "urutan_cabang": 5,
            "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
            "ip_address": "172.16.17.4",
            "luno": "0015",
            "port": "8051",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": "1522FDC26643",
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 44,
            "profil": "YHU.LUWUK10",
            "cabang_kode": "004",
            "cabang_text": "004-Luwuk",
            "urutan_cabang": 6,
            "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
            "ip_address": "172.16.17.5",
            "luno": "0229",
            "port": "8254",
            "vendor_name": "ASSINDO",
            "serial_number": "H2410D00133",
            "denom": "100",
            "tipe_mesin": "ATM YIHUA",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 45,
            "profil": "YHU.LUWUK11",
            "cabang_kode": "004",
            "cabang_text": "004-Luwuk",
            "urutan_cabang": 7,
            "nama_lokasi": "Galeri ATM Kantor Cabang Luwuk",
            "ip_address": "172.16.17.7",
            "luno": "0230",
            "port": "8255",
            "vendor_name": "ASSINDO",
            "serial_number": "H2410D00136",
            "denom": "100",
            "tipe_mesin": "ATM YIHUA",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 46,
            "profil": "CRM.LUWUK12",
            "cabang_kode": "004",
            "cabang_text": "004-Luwuk",
            "urutan_cabang": 8,
            "nama_lokasi": "Digital Lounge Cabang Luwuk",
            "ip_address": "172.16.75.38",
            "luno": "0430",
            "port": "8302",
            "vendor_name": "COLLEGA INTI PRATAMA",
            "serial_number": null,
            "denom": "50/100",
            "tipe_mesin": "CRM HYOSUNG",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 47,
            "profil": "CRM.LUWUK13",
            "cabang_kode": "004",
            "cabang_text": "004-Luwuk",
            "urutan_cabang": 9,
            "nama_lokasi": "Digital Lounge Cabang Luwuk",
            "ip_address": "172.16.75.36",
            "luno": "0431",
            "port": "8303",
            "vendor_name": "COLLEGA INTI PRATAMA",
            "serial_number": null,
            "denom": "50/100",
            "tipe_mesin": "CRM HYOSUNG",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 48,
            "profil": "CRM.LUWUK14",
            "cabang_kode": "004",
            "cabang_text": "004-Luwuk",
            "urutan_cabang": 10,
            "nama_lokasi": "Digital Lounge Cabang Luwuk",
            "ip_address": "172.16.75.37",
            "luno": "0432",
            "port": "8304",
            "vendor_name": "COLLEGA INTI PRATAMA",
            "serial_number": null,
            "denom": "50/100",
            "tipe_mesin": "CRM HYOSUNG",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 49,
            "profil": "CRM.BUNGKU",
            "cabang_kode": "005",
            "cabang_text": "005-Bungku",
            "urutan_cabang": 1,
            "nama_lokasi": "Galeri ATM Kantor Cabang Bungku",
            "ip_address": "192.168.227.146",
            "luno": "0188",
            "port": "8210",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0091",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 50,
            "profil": "GRG.BUNGKU7",
            "cabang_kode": "005",
            "cabang_text": "005-Bungku",
            "urutan_cabang": 2,
            "nama_lokasi": "Gardu ATM Kantor Bupati Bungku",
            "ip_address": "175.10.7.3",
            "luno": "0489",
            "port": "8359",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 51,
            "profil": "GRG.BUNGKU3",
            "cabang_kode": "005",
            "cabang_text": "005-Bungku",
            "urutan_cabang": 3,
            "nama_lokasi": "Gardu ATM KC Bungku lama",
            "ip_address": "192.168.225.203",
            "luno": "0487",
            "port": "8357",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 52,
            "profil": "GRG.BUNGKU1",
            "cabang_kode": "005",
            "cabang_text": "005-Bungku",
            "urutan_cabang": 4,
            "nama_lokasi": "Galeri ATM Kantor Cabang Bungku",
            "ip_address": "175.10.7.2",
            "luno": "0488",
            "port": "8358",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 53,
            "profil": "GRG.BUNGKU2",
            "cabang_kode": "005",
            "cabang_text": "005-Bungku",
            "urutan_cabang": 5,
            "nama_lokasi": "Gardu ATM Witaponda",
            "ip_address": "175.12.10.10",
            "luno": "0486",
            "port": "8364",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 54,
            "profil": "CRM.BUNGKU4",
            "cabang_kode": "005",
            "cabang_text": "005-Bungku",
            "urutan_cabang": 6,
            "nama_lokasi": "Digital Lounge Cabang Bungku",
            "ip_address": "172.16.75.2",
            "luno": "0244",
            "port": "8296",
            "vendor_name": "COLLEGA INTI PRATAMA",
            "serial_number": null,
            "denom": "50/100",
            "tipe_mesin": "CRM HYOSUNG",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 55,
            "profil": "CRM.BUNGKU5",
            "cabang_kode": "005",
            "cabang_text": "005-Bungku",
            "urutan_cabang": 7,
            "nama_lokasi": "Digital Lounge Cabang Bungku",
            "ip_address": "172.16.75.3",
            "luno": "0245",
            "port": "8297",
            "vendor_name": "COLLEGA INTI PRATAMA",
            "serial_number": null,
            "denom": "50/100",
            "tipe_mesin": "CRM HYOSUNG",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 56,
            "profil": "CRM.BUNGKU6",
            "cabang_kode": "005",
            "cabang_text": "005-Bungku",
            "urutan_cabang": 8,
            "nama_lokasi": "Digital Lounge Cabang Bungku",
            "ip_address": "172.16.75.4",
            "luno": "0246",
            "port": "8298",
            "vendor_name": "COLLEGA INTI PRATAMA",
            "serial_number": null,
            "denom": "50/100",
            "tipe_mesin": "CRM HYOSUNG",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 57,
            "profil": "GRG.SLKN5",
            "cabang_kode": "006",
            "cabang_text": "006-Salakan",
            "urutan_cabang": 1,
            "nama_lokasi": "Gardu ATM Kantor Keuangan",
            "ip_address": "175.12.37.2",
            "luno": "0508",
            "port": "8378",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 58,
            "profil": "WCR.SLKN2",
            "cabang_kode": "006",
            "cabang_text": "006-Salakan",
            "urutan_cabang": 2,
            "nama_lokasi": "Galeri ATM Kantor Cabang Salakan",
            "ip_address": "172.16.18.2",
            "luno": "0210",
            "port": "8234",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701752",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 59,
            "profil": "GRG.SLKN6",
            "cabang_kode": "006",
            "cabang_text": "006-Salakan",
            "urutan_cabang": 3,
            "nama_lokasi": "Gardu ATM Pertokoan",
            "ip_address": "192.168.227.46",
            "luno": "0509",
            "port": "8379",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 60,
            "profil": "CRM.SALAKAN",
            "cabang_kode": "006",
            "cabang_text": "006-Salakan",
            "urutan_cabang": 4,
            "nama_lokasi": "Galeri ATM Kantor Cabang Salakan",
            "ip_address": "172.16.18.3",
            "luno": "0187",
            "port": "8209",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0096",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 61,
            "profil": "WCR.SLKN",
            "cabang_kode": "006",
            "cabang_text": "006-Salakan",
            "urutan_cabang": 5,
            "nama_lokasi": "Galeri ATM RSUD Salakan",
            "ip_address": "175.12.27.3",
            "luno": "0157",
            "port": "8170",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "J821004732",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 62,
            "profil": "YHU.SLKN",
            "cabang_kode": "006",
            "cabang_text": "006-Salakan",
            "urutan_cabang": 6,
            "nama_lokasi": "Galeri ATM Kantor Cabang Salakan",
            "ip_address": "192.168.225.212",
            "luno": "0233",
            "port": "8258",
            "vendor_name": "ASSINDO",
            "serial_number": "H2410D00131",
            "denom": "100",
            "tipe_mesin": "ATM YIHUA",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 63,
            "profil": "CRM.SIGI1",
            "cabang_kode": "007",
            "cabang_text": "007-Sigi",
            "urutan_cabang": 1,
            "nama_lokasi": "Kantor Cabang Sigi",
            "ip_address": "172.16.29.4",
            "luno": "0179",
            "port": "8201",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0098",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 64,
            "profil": "GRG.SIGI3",
            "cabang_kode": "007",
            "cabang_text": "007-Sigi",
            "urutan_cabang": 2,
            "nama_lokasi": "Kantor Cabang Sigi",
            "ip_address": "172.16.29.2",
            "luno": "0442",
            "port": "8312",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 65,
            "profil": "WCR.SIGI",
            "cabang_kode": "007",
            "cabang_text": "007-Sigi",
            "urutan_cabang": 3,
            "nama_lokasi": "Puskesmas Kaleke Sigi",
            "ip_address": "192.168.227.130",
            "luno": "0159",
            "port": "8172",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "J821004736",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 66,
            "profil": "GRG.SIGI2",
            "cabang_kode": "007",
            "cabang_text": "007-Sigi",
            "urutan_cabang": 4,
            "nama_lokasi": "Kantor Bupati Sigi",
            "ip_address": "175.13.10.4",
            "luno": "0493",
            "port": "8363",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 67,
            "profil": "GRG.SIGI4",
            "cabang_kode": "007",
            "cabang_text": "007-Sigi",
            "urutan_cabang": 5,
            "nama_lokasi": "Kelapa Gading",
            "ip_address": "172.16.50.58",
            "luno": "0495",
            "port": "8365",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 68,
            "profil": "GRG.PALBAR5",
            "cabang_kode": "008",
            "cabang_text": "008-Palu Barat",
            "urutan_cabang": 1,
            "nama_lokasi": "Galeri ATM Cabang Palu Barat",
            "ip_address": "172.16.45.2",
            "luno": "0460",
            "port": "8330",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 69,
            "profil": "WCR.PALBAR",
            "cabang_kode": "008",
            "cabang_text": "008-Palu Barat",
            "urutan_cabang": 2,
            "nama_lokasi": "Galeri ATM Swiss Bel Hotel",
            "ip_address": "175.12.19.2",
            "luno": "0209",
            "port": "8233",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701730",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 70,
            "profil": "GRG.PALBAR4",
            "cabang_kode": "008",
            "cabang_text": "008-Palu Barat",
            "urutan_cabang": 3,
            "nama_lokasi": "Kantor Museum Palu",
            "ip_address": "175.12.43.2",
            "luno": "0451",
            "port": "8321",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 71,
            "profil": "GRG.PALBAR6",
            "cabang_kode": "008",
            "cabang_text": "008-Palu Barat",
            "urutan_cabang": 4,
            "nama_lokasi": "Galeri ATM Cabang Palu Barat",
            "ip_address": "175.10.3.3",
            "luno": "0461",
            "port": "8331",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 72,
            "profil": "CRM.PALUBARAT",
            "cabang_kode": "008",
            "cabang_text": "008-Palu Barat",
            "urutan_cabang": 5,
            "nama_lokasi": "Galeri ATM Cabang Palu Barat",
            "ip_address": "172.16.45.5",
            "luno": "0180",
            "port": "8202",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0100",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 73,
            "profil": "GRG.PALBAR3",
            "cabang_kode": "008",
            "cabang_text": "008-Palu Barat",
            "urutan_cabang": 6,
            "nama_lokasi": "Swalayan Smart Kitchen",
            "ip_address": "175.12.21.3",
            "luno": "0444",
            "port": "8314",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 74,
            "profil": "GRG.JAKARTA",
            "cabang_kode": "009",
            "cabang_text": "009-Jakarta",
            "urutan_cabang": 1,
            "nama_lokasi": "Kantor Cabang Jakarta",
            "ip_address": "175.10.11.4",
            "luno": "0437",
            "port": "8309",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 75,
            "profil": "GRG.DGL3",
            "cabang_kode": "101",
            "cabang_text": "101-Donggala",
            "urutan_cabang": 1,
            "nama_lokasi": "SPBU Donggala",
            "ip_address": "172.16.50.22",
            "luno": "0443",
            "port": "8313",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 76,
            "profil": "CRM.DONGGALA",
            "cabang_kode": "101",
            "cabang_text": "101-Donggala",
            "urutan_cabang": 2,
            "nama_lokasi": "Kantor Cabang Donggala",
            "ip_address": "172.16.12.4",
            "luno": "0181",
            "port": "8203",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0097",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 77,
            "profil": "YHU.DGL2",
            "cabang_kode": "101",
            "cabang_text": "101-Donggala",
            "urutan_cabang": 3,
            "nama_lokasi": "Kantor Cabang Donggala",
            "ip_address": "172.16.12.3",
            "luno": "0228",
            "port": "8253",
            "vendor_name": "ASSINDO",
            "serial_number": "H2410D00137",
            "denom": "100",
            "tipe_mesin": "ATM YIHUA",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 78,
            "profil": "DBL.PRGI",
            "cabang_kode": "102",
            "cabang_text": "102-Parigi",
            "urutan_cabang": 1,
            "nama_lokasi": "Alfamidi Toboli Parigi",
            "ip_address": "172.16.50.90",
            "luno": "0006",
            "port": "8006",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": "1522FDC26650",
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 79,
            "profil": "CRM.PARIGI",
            "cabang_kode": "102",
            "cabang_text": "102-Parigi",
            "urutan_cabang": 2,
            "nama_lokasi": "Kantor Cabang Parigi",
            "ip_address": "192.168.225.134",
            "luno": "0182",
            "port": "8204",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0094",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 80,
            "profil": "WCR.KCPARIGI",
            "cabang_kode": "102",
            "cabang_text": "102-Parigi",
            "urutan_cabang": 3,
            "nama_lokasi": "Kantor Cabang Parigi",
            "ip_address": "192.168.225.132",
            "luno": "0107",
            "port": "8227",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701733",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 81,
            "profil": "GRG.PRG1",
            "cabang_kode": "102",
            "cabang_text": "102-Parigi",
            "urutan_cabang": 4,
            "nama_lokasi": "RSUD Anuntaloko",
            "ip_address": "175.12.4.2",
            "luno": "0475",
            "port": "8345",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 82,
            "profil": "GRG.PRG2",
            "cabang_kode": "102",
            "cabang_text": "102-Parigi",
            "urutan_cabang": 5,
            "nama_lokasi": "Kantor Bupati Parigi",
            "ip_address": "172.16.50.106",
            "luno": "0476",
            "port": "8346",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 83,
            "profil": "WCR.PRGI",
            "cabang_kode": "102",
            "cabang_text": "102-Parigi",
            "urutan_cabang": 6,
            "nama_lokasi": "Alfamidi Parigi",
            "ip_address": "172.16.50.42",
            "luno": "0161",
            "port": "8175",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "J821004733",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 84,
            "profil": "GRG.LAMBUNU1",
            "cabang_kode": "103",
            "cabang_text": "103-Lambunu",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Lambunu",
            "ip_address": "175.11.5.2",
            "luno": "0471",
            "port": "8341",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 85,
            "profil": "GRG.LABEAN1",
            "cabang_kode": "104",
            "cabang_text": "104-KCP Labean",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Labesan",
            "ip_address": "175.11.13.2",
            "luno": "0447",
            "port": "8347",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 86,
            "profil": "WCR.SIOYONG",
            "cabang_kode": "104",
            "cabang_text": "104-KCP Labean",
            "urutan_cabang": 2,
            "nama_lokasi": "Alfamidi Sioyong",
            "ip_address": "192.168.227.106",
            "luno": "0156",
            "port": "8169",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG8000252",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 87,
            "profil": "GRG.TOLAI1",
            "cabang_kode": "105",
            "cabang_text": "105-Tolai",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Tolai",
            "ip_address": "172.16.55.210",
            "luno": "0474",
            "port": "8344",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 88,
            "profil": "GRG.TINOMBO1",
            "cabang_kode": "106",
            "cabang_text": "106-Tinombo",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Tinombo",
            "ip_address": "172.16.51.3",
            "luno": "0470",
            "port": "8340",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 89,
            "profil": "GRG.TINOMBALA1",
            "cabang_kode": "107",
            "cabang_text": "107-Tinombala",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Tinombala",
            "ip_address": "172.16.49.2",
            "luno": "0466",
            "port": "8336",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 90,
            "profil": "DBL.KOTARAYA",
            "cabang_kode": "108",
            "cabang_text": "108-Kotaraya",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Kotaraya",
            "ip_address": "172.16.54.2",
            "luno": "0235",
            "port": "8261",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": "1522FDC26653",
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 91,
            "profil": "CRM.BUOL",
            "cabang_kode": "201",
            "cabang_text": "201-Buol",
            "urutan_cabang": 1,
            "nama_lokasi": "Kantor Cabang Buol",
            "ip_address": "172.16.15.3",
            "luno": "0192",
            "port": "8214",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0093",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 92,
            "profil": "WCR.BUOL2",
            "cabang_kode": "201",
            "cabang_text": "201-Buol",
            "urutan_cabang": 2,
            "nama_lokasi": "SPBU Buol",
            "ip_address": "175.12.3.2",
            "luno": "0212",
            "port": "8237",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701738",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 93,
            "profil": "GRG.BUOL3",
            "cabang_kode": "201",
            "cabang_text": "201-Buol",
            "urutan_cabang": 3,
            "nama_lokasi": "RSUD Buol",
            "ip_address": "192.168.227.22",
            "luno": "0485",
            "port": "8355",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 94,
            "profil": "GRG.BUOL4",
            "cabang_kode": "201",
            "cabang_text": "201-Buol",
            "urutan_cabang": 4,
            "nama_lokasi": "Indomaret Busak",
            "ip_address": "192.168.227.26",
            "luno": "0483",
            "port": "8353",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 95,
            "profil": "GRG.BUOL5",
            "cabang_kode": "201",
            "cabang_text": "201-Buol",
            "urutan_cabang": 5,
            "nama_lokasi": "Kantor Keuangan Buol",
            "ip_address": "175.12.25.2",
            "luno": "0484",
            "port": "8354",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 96,
            "profil": "WCR.BUOL",
            "cabang_kode": "201",
            "cabang_text": "201-Buol",
            "urutan_cabang": 6,
            "nama_lokasi": "Indomaret Bunobogu",
            "ip_address": "172.16.65.122",
            "luno": "0158",
            "port": "8171",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "J821004731",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 97,
            "profil": "YHU.BUOL7",
            "cabang_kode": "201",
            "cabang_text": "201-Buol",
            "urutan_cabang": 7,
            "nama_lokasi": "Kantor Cabang Buol",
            "ip_address": "192.168.229.4",
            "luno": "0231",
            "port": "8256",
            "vendor_name": "ASSINDO",
            "serial_number": "H2410D00128",
            "denom": "100",
            "tipe_mesin": "ATM YIHUA",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 98,
            "profil": "WCR.SONI",
            "cabang_kode": "202",
            "cabang_text": "202-Soni",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Soni",
            "ip_address": "192.168.229.35",
            "luno": "0211",
            "port": "8236",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701736",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 99,
            "profil": "GRG.PALELEH",
            "cabang_kode": "211",
            "cabang_text": "211-Paleleh",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Paleleh",
            "ip_address": "172.16.24.3",
            "luno": "0490",
            "port": "8360",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 100,
            "profil": "GRG.AMPN6",
            "cabang_kode": "301",
            "cabang_text": "301-Ampana",
            "urutan_cabang": 1,
            "nama_lokasi": "Alfamidi Tojo",
            "ip_address": "192.168.227.70",
            "luno": "0504",
            "port": "8374",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 101,
            "profil": "GRG.AMPN3",
            "cabang_kode": "301",
            "cabang_text": "301-Ampana",
            "urutan_cabang": 2,
            "nama_lokasi": "Maraja Mart",
            "ip_address": "172.16.50.26",
            "luno": "0502",
            "port": "8372",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 102,
            "profil": "GRG.AMPN5",
            "cabang_kode": "301",
            "cabang_text": "301-Ampana",
            "urutan_cabang": 3,
            "nama_lokasi": "Kantor Bupati Ampana",
            "ip_address": "172.16.42.2",
            "luno": "0503",
            "port": "8373",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 103,
            "profil": "GRG.AMPN7",
            "cabang_kode": "301",
            "cabang_text": "301-Ampana",
            "urutan_cabang": 4,
            "nama_lokasi": "Indomaret Ampana",
            "ip_address": "172.16.50.82",
            "luno": "0505",
            "port": "8375",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 104,
            "profil": "CRM.AMPANA",
            "cabang_kode": "301",
            "cabang_text": "301-Ampana",
            "urutan_cabang": 5,
            "nama_lokasi": "Kantor Cabang Ampana",
            "ip_address": "172.16.22.3",
            "luno": "0184",
            "port": "8206",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0092",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 105,
            "profil": "WCR.AMP1",
            "cabang_kode": "301",
            "cabang_text": "301-Ampana",
            "urutan_cabang": 6,
            "nama_lokasi": "Kantor Cabang Ampana",
            "ip_address": "172.16.22.253",
            "luno": "0166",
            "port": "8268",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "J821004737",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 106,
            "profil": "YHU.AMP4",
            "cabang_kode": "301",
            "cabang_text": "301-Ampana",
            "urutan_cabang": 7,
            "nama_lokasi": "Kantor Cabang Ampana",
            "ip_address": "172.16.22.4",
            "luno": "0227",
            "port": "8266",
            "vendor_name": "ASSINDO",
            "serial_number": "H2410D00129",
            "denom": "100",
            "tipe_mesin": "ATM YIHUA",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 107,
            "profil": "DBL..AMP2",
            "cabang_kode": "301",
            "cabang_text": "301-Ampana",
            "urutan_cabang": 8,
            "nama_lokasi": "Pasar Ampana",
            "ip_address": "175.12.51.2",
            "luno": "0057",
            "port": "8057",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": "1522FDC13567",
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 108,
            "profil": "GRG.WAKAI1",
            "cabang_kode": "302",
            "cabang_text": "302-Wakai",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Wakai",
            "ip_address": "175.11.1.6",
            "luno": "0506",
            "port": "8376",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 109,
            "profil": "GRG.TTNA1",
            "cabang_kode": "303",
            "cabang_text": "303-Tentena",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Tentena",
            "ip_address": "172.16.43.2",
            "luno": "0465",
            "port": "8335",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 110,
            "profil": "YHU.TTNA2",
            "cabang_kode": "303",
            "cabang_text": "303-Tentena",
            "urutan_cabang": 2,
            "nama_lokasi": "KCP Tentena",
            "ip_address": "172.16.43.4",
            "luno": "0232",
            "port": "8257",
            "vendor_name": "ASSINDO",
            "serial_number": "H2410D00135",
            "denom": "100",
            "tipe_mesin": "ATM YIHUA",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 111,
            "profil": "DBL.PENDOLO1",
            "cabang_kode": "304",
            "cabang_text": "304-Pendolo",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Pendolo",
            "ip_address": "175.10.14.3",
            "luno": "0464",
            "port": "8334",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 112,
            "profil": "DBL.NAPU",
            "cabang_kode": "305",
            "cabang_text": "305-Napu",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Napu",
            "ip_address": "175.10.15.2",
            "luno": "0219",
            "port": "8244",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": "1522FDC25162",
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 113,
            "profil": "DBL.TAMBARANA1",
            "cabang_kode": "306",
            "cabang_text": "306-Tambarana",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Tambarana",
            "ip_address": "172.16.53.2",
            "luno": "0234",
            "port": "8259",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": "1522FDC26649",
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 114,
            "profil": "GRG.KODAL3",
            "cabang_kode": "401",
            "cabang_text": "401-Kolonodale",
            "urutan_cabang": 1,
            "nama_lokasi": "SPBU KOLONODALE",
            "ip_address": "172.16.50.114",
            "luno": "0479",
            "port": "8349",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 115,
            "profil": "WCR.MORO2",
            "cabang_kode": "401",
            "cabang_text": "401-Kolonodale",
            "urutan_cabang": 2,
            "nama_lokasi": "Kantor Cabang Kolonodale",
            "ip_address": "172.16.20.2",
            "luno": "0155",
            "port": "8168",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG800344",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 116,
            "profil": "CRM.KOLONODALE",
            "cabang_kode": "401",
            "cabang_text": "401-Kolonodale",
            "urutan_cabang": 3,
            "nama_lokasi": "Kantor Cabang Kolonodale",
            "ip_address": "172.16.20.3",
            "luno": "0189",
            "port": "8211",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0101",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 117,
            "profil": "YHU.KODAL4",
            "cabang_kode": "401",
            "cabang_text": "401-Kolonodale",
            "urutan_cabang": 4,
            "nama_lokasi": "Kantor Cabang Kolonodale",
            "ip_address": "192.168.225.150",
            "luno": "0225",
            "port": "8250",
            "vendor_name": "ASSINDO",
            "serial_number": "H2410D00130",
            "denom": "100",
            "tipe_mesin": "ATM YIHUA",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 118,
            "profil": "YHU.KODAL5",
            "cabang_kode": "401",
            "cabang_text": "401-Kolonodale",
            "urutan_cabang": 5,
            "nama_lokasi": "Kantor Cabang Kolonodale",
            "ip_address": "172.16.50.74",
            "luno": "0226",
            "port": "8251",
            "vendor_name": "ASSINDO",
            "serial_number": "H2410D00134",
            "denom": "100",
            "tipe_mesin": "ATM YIHUA",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 119,
            "profil": "GRG.BALUT3",
            "cabang_kode": "402",
            "cabang_text": "402-Banggai Laut",
            "urutan_cabang": 1,
            "nama_lokasi": "Balaikota Banggai Laut",
            "ip_address": "175.12.44.2",
            "luno": "0511",
            "port": "8381",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 120,
            "profil": "GRG.BALUT5",
            "cabang_kode": "402",
            "cabang_text": "402-Banggai Laut",
            "urutan_cabang": 2,
            "nama_lokasi": "RSUD Banggai Laut",
            "ip_address": "192.168.227.50",
            "luno": "0512",
            "port": "8382",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 121,
            "profil": "GRG.BALUT2",
            "cabang_kode": "402",
            "cabang_text": "402-Banggai Laut",
            "urutan_cabang": 3,
            "nama_lokasi": "Kantor Cabang Banggai Laut",
            "ip_address": "172.16.39.3",
            "luno": "0510",
            "port": "8380",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 122,
            "profil": "CRM.BALUT",
            "cabang_kode": "402",
            "cabang_text": "402-Banggai Laut",
            "urutan_cabang": 4,
            "nama_lokasi": "Kantor Cabang Banggai Laut",
            "ip_address": "172.16.39.4",
            "luno": "0186",
            "port": "8208",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0095",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 123,
            "profil": "DBL.BALUT4",
            "cabang_kode": "402",
            "cabang_text": "402-Banggai Laut",
            "urutan_cabang": 5,
            "nama_lokasi": "Kantor Cabang Banggai Laut",
            "ip_address": "172.16.39.5",
            "luno": "0238",
            "port": "8291",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": "1522FDC09152",
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 124,
            "profil": "GRG.BETELEME1",
            "cabang_kode": "403",
            "cabang_text": "403-Beteleme",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Beteleme",
            "ip_address": "192.168.228.30",
            "luno": "0478",
            "port": "8352",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 125,
            "profil": "GRG.BATUI1",
            "cabang_kode": "404",
            "cabang_text": "404-Batui",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Batui",
            "ip_address": "172.16.55.163",
            "luno": "0517",
            "port": "8387",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 126,
            "profil": "WCR.KASBATUI2",
            "cabang_kode": "404",
            "cabang_text": "404-Batui",
            "urutan_cabang": 2,
            "nama_lokasi": "Polsek Kintom",
            "ip_address": "175.12.34.3",
            "luno": "0427",
            "port": "8299",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701707",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 127,
            "profil": "WCR.TOILI",
            "cabang_kode": "405",
            "cabang_text": "405-Toili",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Toili",
            "ip_address": "175.10.4.5",
            "luno": "0103",
            "port": "8235",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701729",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 128,
            "profil": "WCR.TOILI2",
            "cabang_kode": "405",
            "cabang_text": "405-Toili",
            "urutan_cabang": 2,
            "nama_lokasi": "Pasar Toili Barat",
            "ip_address": "192.168.227.122",
            "luno": "0165",
            "port": "8179",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "J821004734",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 129,
            "profil": "DBL.MASAMA",
            "cabang_kode": "406",
            "cabang_text": "406-Masama",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Masama",
            "ip_address": "175.10.16.3",
            "luno": "0236",
            "port": "8262",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": "1522FDC09155",
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 130,
            "profil": "DBL.BUNTA01",
            "cabang_kode": "407",
            "cabang_text": "407-Bunta",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Bunta",
            "ip_address": "172.16.56.3",
            "luno": "0237",
            "port": "8290",
            "vendor_name": "KOPERASI BANK SULTENG",
            "serial_number": "1522FDC13574",
            "denom": "100",
            "tipe_mesin": "ATM OPTEVA 522",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 131,
            "profil": "WCR.MAMOSALATO",
            "cabang_kode": "411",
            "cabang_text": "411-Mamosalato",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Mamosalato",
            "ip_address": "192.168.228.90",
            "luno": "0160",
            "port": "8174",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "J821004738",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 132,
            "profil": "WCR.TOMATA",
            "cabang_kode": "412",
            "cabang_text": "412-Tomata",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Tomata",
            "ip_address": "175.11.6.3",
            "luno": "0208",
            "port": "8232",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701735",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 133,
            "profil": "GRG.BATURUBE",
            "cabang_kode": "413",
            "cabang_text": "413-Baturube",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Baturube",
            "ip_address": "175.11.9.2",
            "luno": "0516",
            "port": "8386",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 134,
            "profil": "GRG.BHMTF1",
            "cabang_kode": "501",
            "cabang_text": "501-Bahomotefe",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Bahomotefe",
            "ip_address": "175.11.4.3",
            "luno": "0491",
            "port": "8361",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 135,
            "profil": "GRG.BHMTF2",
            "cabang_kode": "501",
            "cabang_text": "501-Bahomotefe",
            "urutan_cabang": 2,
            "nama_lokasi": "KCP Bahomotefe",
            "ip_address": "175.11.4.5",
            "luno": "0492",
            "port": "8362",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 136,
            "profil": "GRG.BHDP1",
            "cabang_kode": "502",
            "cabang_text": "502-Bahodopi",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Bahodopi",
            "ip_address": "175.10.8.8",
            "luno": "0496",
            "port": "8366",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 137,
            "profil": "RBR.BHDP3",
            "cabang_kode": "502",
            "cabang_text": "502-Bahodopi",
            "urutan_cabang": 2,
            "nama_lokasi": "KCP Bahodopi",
            "ip_address": "192.168.229.23",
            "luno": "0501",
            "port": "8371",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 138,
            "profil": "GRG.BHDP4",
            "cabang_kode": "502",
            "cabang_text": "502-Bahodopi",
            "urutan_cabang": 3,
            "nama_lokasi": "Galeri Karim Labota",
            "ip_address": "175.12.36.4",
            "luno": "0497",
            "port": "8367",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 139,
            "profil": "GRG.BHDP5",
            "cabang_kode": "502",
            "cabang_text": "502-Bahodopi",
            "urutan_cabang": 4,
            "nama_lokasi": "Rusunawa PT SMI",
            "ip_address": "192.168.227.114",
            "luno": "0498",
            "port": "8368",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 140,
            "profil": "GRG.BHDP6",
            "cabang_kode": "502",
            "cabang_text": "502-Bahodopi",
            "urutan_cabang": 5,
            "nama_lokasi": "SPBU Bahodopi",
            "ip_address": "172.16.50.66",
            "luno": "0500",
            "port": "8370",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 141,
            "profil": "GRG.BHDP7",
            "cabang_kode": "502",
            "cabang_text": "502-Bahodopi",
            "urutan_cabang": 6,
            "nama_lokasi": "KCP Bahodopi",
            "ip_address": "175.10.8.9",
            "luno": "0499",
            "port": "8369",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 142,
            "profil": "CRM.BAHODOPI",
            "cabang_kode": "502",
            "cabang_text": "502-Bahodopi",
            "urutan_cabang": 7,
            "nama_lokasi": "KCP Bahodopi",
            "ip_address": "175.10.8.4",
            "luno": "0190",
            "port": "8212",
            "vendor_name": "ASSINDO",
            "serial_number": "B2209D0102",
            "denom": "50/100",
            "tipe_mesin": "CRM YIHUA",
            "kategori": "CRM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 143,
            "profil": "WCR.MBHDP",
            "cabang_kode": "502",
            "cabang_text": "502-Bahodopi",
            "urutan_cabang": 8,
            "nama_lokasi": "ATM Mobil_KCP Bahodopi",
            "ip_address": "192.168.225.228",
            "luno": "0152",
            "port": "8165",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701742",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 144,
            "profil": "WCR.BHDP2",
            "cabang_kode": "502",
            "cabang_text": "502-Bahodopi",
            "urutan_cabang": 9,
            "nama_lokasi": "Bungku Pesisir",
            "ip_address": "192.168.227.138",
            "luno": "0218",
            "port": "8243",
            "vendor_name": "SRISHINDU INFORMATIKA",
            "serial_number": "56HG701739",
            "denom": "100",
            "tipe_mesin": "ATM WINCOR Pro Cash 480N",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 145,
            "profil": "GRG.KULAWI1",
            "cabang_kode": "701",
            "cabang_text": "701-Kulawi",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Kulawi",
            "ip_address": "172.16.65.66",
            "luno": "0462",
            "port": "8332",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 146,
            "profil": "GRG.TAWAELI1",
            "cabang_kode": "801",
            "cabang_text": "801-Capem Tawaeli",
            "urutan_cabang": 1,
            "nama_lokasi": "KCP Tawaeli",
            "ip_address": "172.16.48.2",
            "luno": "0472",
            "port": "8342",
            "vendor_name": "PT KIS",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        },
        {
            "no": 147,
            "profil": "DBL.TOAYA1",
            "cabang_kode": "801",
            "cabang_text": "801-Capem Tawaeli",
            "urutan_cabang": 2,
            "nama_lokasi": "Kantor Camat Toaya",
            "ip_address": "175.12.26.3",
            "luno": "0473",
            "port": "8343",
            "vendor_name": "ASSINDO",
            "serial_number": null,
            "denom": "100",
            "tipe_mesin": "ATM GRG H22VL",
            "kategori": "ATM",
            "is_hibah": false,
            "rek_ia": null,
            "status": "Aktif"
        }
]
JSON;

        foreach (json_decode($terminalsJson, true) as $item) {
            Terminal::updateOrCreate(
                ['profil' => $item['profil']],
                [
                    'cabang_id' => $cabangMap[$item['cabang_kode']] ?? null,
                    'cabang_text' => $item['cabang_text'],
                    'urutan_cabang' => $item['urutan_cabang'],
                    'nama_lokasi' => $item['nama_lokasi'],
                    'ip_address' => $item['ip_address'],
                    'luno' => $item['luno'],
                    'port' => $item['port'],
                    'vendor_id' => $vendorMap[$item['vendor_name']] ?? null,
                    'vendor_text' => $item['vendor_name'],
                    'serial_number' => $item['serial_number'],
                    'denom' => $item['denom'],
                    'tipe_mesin' => $item['tipe_mesin'],
                    'kategori' => $item['kategori'],
                    'is_hibah' => $item['is_hibah'],
                    'rek_ia' => $item['rek_ia'],
                    'status' => $item['status'],
                ]
            );
        }
    }
}
